[build]
  command = "pnpm doc:generate && pnpm build:pkg && pnpm build:doc"
  publish = "apps/docs/.next"
  environment = { NODE_OPTIONS = "--max-old-space-size=8192" }

[[plugins]]
  package = "@netlify/plugin-nextjs"
