name: Save Turborepo cache

runs:
    using: composite
    steps:
        -   name: Save Turborepo cache
            id: cache-turborepo-save
            if: always() && steps.cache-turborepo-restore.outputs.cache-hit != 'true'
            uses: actions/cache/save@v4
            with:
                key: ${{ steps.cache-turborepo-restore.outputs.cache-primary-key }}
                path: .turbo
