// TODO: this need to be auto generated

/**
 * Example of a file in generate-icon-components (ex: AddIcon.tsx)
 *
 * const AddIcon16 = <svg ........... /> //generated by svgr for add-16.svg
 * const AddIcon24 = <svg ........... /> //generated by svgr for add-24.svg
 * const AddIcon32 = <svg ........... /> //generated by svgr for add-32.svg
 *
 * export const AddIcon = createMultiVariantIcon(AddIcon16, AddIcon24, AddIcon32);
 *
 */

/**
 * Example of the index.ts file in generate-icon-components
 *
 * export * from "./AddIcon.tsx"
 */
