// TODO: this need to be auto generated

// Option 1
/**
 * Example of a file in generate-icon-components (ex: AddIcon.tsx)
 *
 * const AddIcon16 = <svg ........... /> //generated by svgr for add-16.svg
 * const AddIcon24 = <svg ........... /> //generated by svgr for add-24.svg
 * const AddIcon32 = <svg ........... /> //generated by svgr for add-32.svg
 *
 * export const AddIcon = createMultiVariantIcon(AddIcon16, AddIcon24, AddIcon32);
 *
 */

// Option 2
/**
 * Example of a file in generate-icon-components (ex: AddIcon.tsx)
 *
 * import AddIcon16 from "./add-16.svg";
 * import AddIcon24 from "./add-24.svg";
 * import AddIcon32 from "./add-32.svg";
 *
 * export const AddIcon = createMultiVariantIcon(AddIcon16, AddIcon24, AddIcon32);
 *
 */

/**
 * Example of the index.ts file in generate-icon-components
 *
 * export * from "./AddIcon.tsx"
 */
