/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import React, { forwardRef, type Ref, type SVGProps } from "react";

const AddCalendarIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M5.75 1a.75.75 0 0 1 .75.75V2h3v-.25a.75.75 0 1 1 1.5 0V2h2a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h2v-.25A.75.75 0 0 1 5.75 1m3.793 2.5a.75.75 0 0 0 1.415 0H12.5v9h-9v-9h1.543a.75.75 0 0 0 1.414 0zM8 5.25a.75.75 0 0 1 .75.75v1.25H10a.75.75 0 0 1 0 1.5H8.75V10a.75.75 0 0 1-1.5 0V8.75H6a.75.75 0 0 1 0-1.5h1.25V6A.75.75 0 0 1 8 5.25" /></svg>);
const AddCalendarIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M7.753 2.5a.75.75 0 0 1 .75.75V4H15.5v-.75a.75.75 0 0 1 1.5 0V4h1.5A1.5 1.5 0 0 1 20 5.5v13a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 4 18.5v-13A1.5 1.5 0 0 1 5.5 4h1.503v-.75a.75.75 0 0 1 .75-.75m7.747 3v.75a.75.75 0 0 0 1.5 0V5.5h1.5v13h-13v-13h1.503v.75a.75.75 0 0 0 1.5 0V5.5zM12 8a.75.75 0 0 1 .75.75v2.5h2.5a.75.75 0 0 1 0 1.5h-2.5v2.5a.75.75 0 0 1-1.5 0v-2.5h-2.5a.75.75 0 0 1 0-1.5h2.5v-2.5A.75.75 0 0 1 12 8" /></svg>);
const AddCalendarIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M11 4a1 1 0 0 1 1 1v1h8V5a1 1 0 1 1 2 0v1h2a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h2V5a1 1 0 0 1 1-1m9 4v1a1 1 0 1 0 2 0V8h2v16H8V8h2v1a1 1 0 1 0 2 0V8zm-4.033 3a1 1 0 0 1 1 1v2.967H20a1 1 0 0 1 0 2h-3.033V20a1 1 0 1 1-2 0v-3.033H12a1 1 0 1 1 0-2h2.967V12a1 1 0 0 1 1-1" /></svg>);

export const AddCalendarIcon = createIcon(AddCalendarIcon16, AddCalendarIcon24, AddCalendarIcon32, "AddCalendarIcon");