/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import React, { forwardRef, type Ref, type SVGProps } from "react";

const ArrowsOutVerticalIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path d="M11.425 1.999a.75.75 0 0 1 .75.75v8.686l1.548-1.548a.75.75 0 1 1 1.06 1.06l-2.82 2.822a.75.75 0 0 1-1.068.007l-2.829-2.829a.75.75 0 1 1 1.06-1.06l1.55 1.548V2.749a.75.75 0 0 1 .75-.75m-6.308.219 2.828 2.829a.75.75 0 1 1-1.06 1.06L5.337 4.56v8.686a.75.75 0 0 1-1.5 0V4.56L2.29 6.108a.75.75 0 1 1-1.06-1.061l2.819-2.82a.734.734 0 0 1 .264-.176.746.746 0 0 1 .806.167" /></svg>);
const ArrowsOutVerticalIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path d="M15.766 4.002a.75.75 0 0 1 .75.75v12.694l2.199-2.2a.75.75 0 1 1 1.06 1.062l-3.477 3.477-.015.015a.748.748 0 0 1-1.048-.013l-3.479-3.48a.75.75 0 0 1 1.061-1.06l2.199 2.199V4.752a.75.75 0 0 1 .75-.75M8.231 20.006a.75.75 0 0 1-.75-.75V6.563L5.282 8.76a.75.75 0 0 1-1.06-1.06L7.69 4.232a.748.748 0 0 1 1.072-.01L12.24 7.7a.75.75 0 0 1-1.061 1.06L8.981 6.562v12.694a.75.75 0 0 1-.75.75" /></svg>);
const ArrowsOutVerticalIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path d="M20.687 6a1 1 0 0 1 1 1v15.566l2.606-2.606a1 1 0 0 1 1.414 1.414l-4.303 4.303a1.013 1.013 0 0 1-.28.203.996.996 0 0 1-1.144-.193l-4.313-4.313a1 1 0 0 1 1.414-1.414l2.606 2.606V7a1 1 0 0 1 1-1m-9.374 19.98a1 1 0 0 1-1-1V9.414L7.707 12.02a1 1 0 0 1-1.414-1.414l4.302-4.302A1.005 1.005 0 0 1 11.313 6a.997.997 0 0 1 .707.293l4.313 4.313a1 1 0 0 1-1.414 1.414l-2.606-2.606V24.98a1 1 0 0 1-1 1" /></svg>);

export const ArrowsOutVerticalIcon = createIcon(ArrowsOutVerticalIcon16, ArrowsOutVerticalIcon24, ArrowsOutVerticalIcon32, "ArrowsOutVerticalIcon");