/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import React, { forwardRef, type Ref, type SVGProps } from "react";

const ArrowLeftIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M7.395 3.423 3.563 7.255H14.26a.75.75 0 1 1 0 1.5H3.564l3.832 3.832a.75.75 0 1 1-1.061 1.06L1.232 8.544a.75.75 0 0 1-.01-1.07l5.113-5.112a.75.75 0 1 1 1.06 1.06" /></svg>);
const ArrowLeftIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M10.533 5.217a.75.75 0 0 0-1.06 0L3.22 11.47a.75.75 0 0 0 0 1.06l6.252 6.253a.75.75 0 0 0 1.06-1.06l-4.97-4.973h14.687a.75.75 0 0 0 0-1.5H5.56l4.973-4.972a.75.75 0 0 0 0-1.061" /></svg>);
const ArrowLeftIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M14.723 6.29a1 1 0 0 0-1.414 0L4.3 15.298l-.008.008a.997.997 0 0 0 .007 1.421l9.009 9.009a1 1 0 0 0 1.414-1.415L7.4 17h19.612a1 1 0 1 0 0-2H7.427l7.296-7.295a1 1 0 0 0 0-1.415" /></svg>);

export const ArrowLeftIcon = createIcon(ArrowLeftIcon16, ArrowLeftIcon24, ArrowLeftIcon32, "ArrowLeftIcon");