/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import React, { forwardRef, type Ref, type SVGProps } from "react";

const ArrowDownIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M8.006 1.001a.75.75 0 0 0-.75.75v10.697L3.424 8.615a.75.75 0 0 0-1.06 1.061l5.112 5.112a.75.75 0 0 0 1.068-.007l5.105-5.105a.75.75 0 1 0-1.06-1.06l-3.833 3.831V1.751a.75.75 0 0 0-.75-.75" /></svg>);
const ArrowDownIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M12 3.001a.75.75 0 0 0-.75.75v14.687l-4.973-4.972a.75.75 0 1 0-1.061 1.06l6.253 6.253a.748.748 0 0 0 1.06 0l6.253-6.252a.75.75 0 0 0-1.06-1.061l-4.973 4.972V3.751a.75.75 0 0 0-.75-.75" /></svg>);
const ArrowDownIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M15.994 4.006a1 1 0 0 0-1 1v19.586l-7.296-7.295a1 1 0 1 0-1.414 1.414l9 9 .015.016a1 1 0 0 0 1.415 0l9.015-9.016a1 1 0 0 0-1.414-1.414l-7.321 7.321V5.006a1 1 0 0 0-1-1" /></svg>);

export const ArrowDownIcon = createIcon(ArrowDownIcon16, ArrowDownIcon24, ArrowDownIcon32, "ArrowDownIcon");