/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import React, { forwardRef, type Ref, type SVGProps } from "react";

const BarsIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M1.068 2.752a.75.75 0 0 1 .75-.75h12.5a.75.75 0 0 1 0 1.5h-12.5a.75.75 0 0 1-.75-.75m0 5.248a.75.75 0 0 1 .75-.75h12.5a.75.75 0 0 1 0 1.5h-12.5a.75.75 0 0 1-.75-.75m.75 4.5a.75.75 0 0 0 0 1.5h12.5a.75.75 0 0 0 0-1.5h-12.5" /></svg>);
const BarsIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M2.998 5.75a.75.75 0 0 1 .75-.75h16.504a.75.75 0 0 1 0 1.5H3.748a.75.75 0 0 1-.75-.75m0 6.25a.75.75 0 0 1 .75-.75h16.504a.75.75 0 0 1 0 1.5H3.748a.75.75 0 0 1-.75-.75m.75 5.5a.75.75 0 0 0 0 1.5h16.504a.75.75 0 0 0 0-1.5H3.748" /></svg>);
const BarsIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M4 7a1 1 0 0 1 1-1h22a1 1 0 1 1 0 2H5a1 1 0 0 1-1-1m0 9a1 1 0 0 1 1-1h22a1 1 0 1 1 0 2H5a1 1 0 0 1-1-1m1 8a1 1 0 1 0 0 2h22a1 1 0 1 0 0-2z" /></svg>);

export const BarsIcon = createIcon(BarsIcon16, BarsIcon24, BarsIcon32, "BarsIcon");