/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import React, { forwardRef, type Ref, type SVGProps } from "react";

const BentoIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" ref={ref} {...props}><path fill="currentColor" d="M4.4 3.2a1.2 1.2 0 1 1-2.4 0 1.2 1.2 0 0 1 2.4 0m0 4.8A1.2 1.2 0 1 1 2 8a1.2 1.2 0 0 1 2.4 0m0 4.8a1.2 1.2 0 1 1-2.4 0 1.2 1.2 0 0 1 2.4 0m4.8-9.6a1.2 1.2 0 1 1-2.4 0 1.2 1.2 0 0 1 2.4 0m0 4.8a1.2 1.2 0 1 1-2.4 0 1.2 1.2 0 0 1 2.4 0m0 4.8a1.2 1.2 0 1 1-2.4 0 1.2 1.2 0 0 1 2.4 0M14 3.2a1.2 1.2 0 1 1-2.4 0 1.2 1.2 0 0 1 2.4 0M14 8a1.2 1.2 0 1 1-2.4 0A1.2 1.2 0 0 1 14 8m0 4.8a1.2 1.2 0 1 1-2.4 0 1.2 1.2 0 0 1 2.4 0" /></svg>);
const BentoIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" ref={ref} {...props}><path fill="currentColor" d="M13.75 5.75a1.75 1.75 0 1 1-3.5 0 1.75 1.75 0 0 1 3.5 0m0 6.25a1.75 1.75 0 1 1-3.5 0 1.75 1.75 0 0 1 3.5 0m0 6.25a1.75 1.75 0 1 1-3.5 0 1.75 1.75 0 0 1 3.5 0M7.5 5.75a1.75 1.75 0 1 1-3.5 0 1.75 1.75 0 0 1 3.5 0m0 6.25A1.75 1.75 0 1 1 4 12a1.75 1.75 0 0 1 3.5 0m0 6.25a1.75 1.75 0 1 1-3.5 0 1.75 1.75 0 0 1 3.5 0M20 5.75a1.75 1.75 0 1 1-3.5 0 1.75 1.75 0 0 1 3.5 0M20 12a1.75 1.75 0 1 1-3.5 0 1.75 1.75 0 0 1 3.5 0m0 6.25a1.75 1.75 0 1 1-3.5 0 1.75 1.75 0 0 1 3.5 0" /></svg>);
const BentoIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M10 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0m0 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0M8 26a2 2 0 1 0 0-4 2 2 0 0 0 0 4M18 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0m0 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0m-2 10a2 2 0 1 0 0-4 2 2 0 0 0 0 4M26 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0m0 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0m-2 10a2 2 0 1 0 0-4 2 2 0 0 0 0 4" /></svg>);

export const BentoIcon = createIcon(BentoIcon16, BentoIcon24, BentoIcon32, "BentoIcon");