/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import React, { forwardRef, type Ref, type SVGProps } from "react";

const CameraIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="m6.041 4.497.312-.997h3.294l.312.997H6.04m-1.571 0 .56-1.795A1 1 0 0 1 5.986 2h4.03a1 1 0 0 1 .954.702l.561 1.795H14a1 1 0 0 1 1 1V13a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V5.497a1 1 0 0 1 1-1h2.47m.814 1.5H2.5V12.5h11V5.997h-2.784A1.03 1.03 0 0 1 10.64 6H5.36c-.025 0-.05 0-.076-.003M8 10a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5m0 1.5A2.25 2.25 0 1 0 8 7a2.25 2.25 0 0 0 0 4.5" /></svg>);
const CameraIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="m9.132 7.5.429-1h4.879l.428 1zm-.82-1.894A1 1 0 0 1 9.23 5h5.538a1 1 0 0 1 .92.606l.813 1.898H20a1 1 0 0 1 1 1V18a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V8.504a1 1 0 0 1 1-1h3.498zM4.5 9.004V17.5h15V9.004zm7.5 5.748a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3m0 1.5a3 3 0 1 0 0-6 3 3 0 0 0 0 6" /></svg>);
const CameraIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M12.596 8h6.808l.794 2h-8.395zm-2.945 2 1.086-2.738A2 2 0 0 1 12.597 6h6.807a2 2 0 0 1 1.859 1.262L22.349 10H26a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V12a2 2 0 0 1 2-2h3.65m13.492 2H6v12h20V12h-2.857M16 20.184a2.167 2.167 0 1 0 0-4.334 2.167 2.167 0 0 0 0 4.334m0 2a4.167 4.167 0 1 0 0-8.334 4.167 4.167 0 0 0 0 8.334" /></svg>);

export const CameraIcon = createIcon(CameraIcon16, CameraIcon24, CameraIcon32, "CameraIcon");