/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import React, { forwardRef, type Ref, type SVGProps } from "react";

const CaretDownIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M5.81 6.75 8 8.94l2.19-2.19zm-1.487.634c-.787-.788-.23-2.134.884-2.134h5.586c1.114 0 1.671 1.346.884 2.134l-2.793 2.793a1.25 1.25 0 0 1-1.768 0z" /></svg>);
const CaretDownIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="m12 16.229 5.71-5.71H6.29zm6.77-4.65-5.71 5.71a1.5 1.5 0 0 1-2.12 0l-5.71-5.71c-.946-.945-.276-2.56 1.06-2.56h11.42c1.336 0 2.005 1.615 1.06 2.56" /></svg>);
const CaretDownIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="m16 20.58 6.577-6.577H9.423zm7.992-5.163-6.578 6.577a2 2 0 0 1-2.828 0l-6.578-6.577c-1.26-1.26-.367-3.415 1.415-3.415h13.154c1.782 0 2.674 2.155 1.415 3.415" /></svg>);

export const CaretDownIcon = createIcon(CaretDownIcon16, CaretDownIcon24, CaretDownIcon32, "CaretDownIcon");