/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import React, { forwardRef, type Ref, type SVGProps } from "react";

const CaretUpIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M10.19 9.25 8 7.06 5.81 9.25zm1.487-.634c.787.788.23 2.134-.884 2.134H5.207c-1.114 0-1.671-1.346-.884-2.134l2.793-2.793a1.25 1.25 0 0 1 1.768 0z" /></svg>);
const CaretUpIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="m12 7.72-5.71 5.71h11.42zm-6.77 4.649 5.71-5.71a1.5 1.5 0 0 1 2.12 0l5.71 5.71c.946.945.276 2.56-1.06 2.56H6.29c-1.336 0-2.006-1.615-1.06-2.56" /></svg>);
const CaretUpIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="m16 11.428-6.577 6.577h13.154zm-7.992 5.163 6.578-6.577a2 2 0 0 1 2.828 0l6.578 6.577c1.26 1.26.367 3.414-1.415 3.414H9.423c-1.782 0-2.675-2.154-1.415-3.414" /></svg>);

export const CaretUpIcon = createIcon(CaretUpIcon16, CaretUpIcon24, CaretUpIcon32, "CaretUpIcon");