/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import React, { forwardRef, type Ref, type SVGProps } from "react";

const CircleAngleRightIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M13.5 8a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0M15 8A7 7 0 1 1 1 8a7 7 0 0 1 14 0M6.581 5.28a.75.75 0 0 1 1.06-1.06l3.074 3.073a1 1 0 0 1 0 1.414L7.642 11.78a.75.75 0 1 1-1.06-1.06L9.3 8 6.58 5.28" /></svg>);
const CircleAngleRightIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M19.5 12a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0m1.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0M10.208 7.79a.75.75 0 1 1 1.06-1.061l4.564 4.564a1 1 0 0 1 0 1.414l-4.564 4.564a.75.75 0 1 1-1.06-1.06L14.418 12l-4.21-4.21" /></svg>);
const CircleAngleRightIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M26 16c0 5.523-4.477 10-10 10S6 21.523 6 16 10.477 6 16 6s10 4.477 10 10m2 0c0 6.627-5.373 12-12 12S4 22.627 4 16 9.373 4 16 4s12 5.373 12 12m-14.707-5.293a1 1 0 1 1 1.414-1.414l5.823 5.823a1.25 1.25 0 0 1 0 1.768l-5.823 5.823a1 1 0 0 1-1.414-1.414L18.586 16z" /></svg>);

export const CircleAngleRightIcon = createIcon(CircleAngleRightIcon16, CircleAngleRightIcon24, CircleAngleRightIcon32, "CircleAngleRightIcon");