/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import React, { forwardRef, type Ref, type SVGProps } from "react";

const CircleAngleLeftIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M13.5 8a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0M15 8A7 7 0 1 1 1 8a7 7 0 0 1 14 0M9.42 5.28a.75.75 0 0 0-1.06-1.06L5.286 7.293a1 1 0 0 0 0 1.414L8.36 11.78a.75.75 0 0 0 1.06-1.06L6.7 8l2.72-2.72" /></svg>);
const CircleAngleLeftIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M19.5 12a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0m1.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0m-7.209-4.21a.75.75 0 1 0-1.06-1.061l-4.565 4.564a1 1 0 0 0 0 1.414l4.564 4.564a.75.75 0 0 0 1.061-1.06L9.581 12z" /></svg>);
const CircleAngleLeftIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M26 16c0 5.523-4.477 10-10 10S6 21.523 6 16 10.477 6 16 6s10 4.477 10 10m2 0c0 6.627-5.373 12-12 12S4 22.627 4 16 9.373 4 16 4s12 5.373 12 12m-9.293-5.293a1 1 0 1 0-1.414-1.414l-5.823 5.823a1.25 1.25 0 0 0 0 1.768l5.823 5.823a1 1 0 0 0 1.414-1.414L13.414 16z" /></svg>);

export const CircleAngleLeftIcon = createIcon(CircleAngleLeftIcon16, CircleAngleLeftIcon24, CircleAngleLeftIcon32, "CircleAngleLeftIcon");