/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import React, { forwardRef, type Ref, type SVGProps } from "react";

const CollapseRightIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M15.003 2.753a.75.75 0 0 0-1.5 0V13.25a.75.75 0 1 0 1.5 0zM1.753 8.75a.75.75 0 1 1 0-1.5h7.682L6.47 4.28a.75.75 0 0 1 1.062-1.06l4.245 4.251a.75.75 0 0 1 0 1.061L7.53 12.78a.75.75 0 0 1-1.06-1.06l2.968-2.97H1.753" /></svg>);
const CollapseRightIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M19.498 5.75a.75.75 0 0 1 1.5 0v12.5a.75.75 0 0 1-1.5 0zm-6.98.707a.75.75 0 0 0-1.034 1.086l3.893 3.707H3.754a.75.75 0 0 0 0 1.5h11.622l-3.892 3.707a.75.75 0 1 0 1.035 1.086l5.25-5a.75.75 0 0 0 0-1.086l-5.25-5" /></svg>);
const CollapseRightIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M26 7a1 1 0 1 1 2 0v18a1 1 0 1 1-2 0zM5 15.003a1 1 0 1 0 0 2h14.583l-5.29 5.29a1 1 0 1 0 1.414 1.414l6.953-6.953a.998.998 0 0 0 .34-.751v-.001a.997.997 0 0 0-.293-.71l-7-7a1 1 0 1 0-1.414 1.415l5.296 5.296H5" /></svg>);

export const CollapseRightIcon = createIcon(CollapseRightIcon16, CollapseRightIcon24, CollapseRightIcon32, "CollapseRightIcon");