/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import React, { forwardRef, type Ref, type SVGProps } from "react";

const DismissIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M12.947 4.114a.75.75 0 1 0-1.061-1.06L8 6.938 4.114 3.053a.75.75 0 0 0-1.06 1.061L6.938 8l-3.886 3.886a.75.75 0 0 0 1.061 1.06L8 9.062l3.886 3.886a.75.75 0 0 0 1.06-1.061L9.062 8l3.886-3.886" /></svg>);
const DismissIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M6.697 5.636a.75.75 0 0 0-1.061 1.06L10.94 12l-5.303 5.303a.75.75 0 0 0 1.06 1.061L12 13.061l5.303 5.303a.75.75 0 0 0 1.061-1.06L13.061 12l5.303-5.303a.75.75 0 1 0-1.06-1.061L12 10.939z" /></svg>);
const DismissIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M7.515 23.071a1 1 0 0 0 1.414 1.414l7.07-7.07 7.072 7.07a1 1 0 0 0 1.414-1.414L17.415 16l7.07-7.071a1 1 0 0 0-1.414-1.414L16 14.585l-7.071-7.07a1 1 0 0 0-1.414 1.414L14.585 16l-7.07 7.071" /></svg>);

export const DismissIcon = createIcon(DismissIcon16, DismissIcon24, DismissIcon32, "DismissIcon");