/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import React, { forwardRef, type Ref, type SVGProps } from "react";

const MailIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M2.5 4.309V12.5h11V4.309L8.836 8.506a1.25 1.25 0 0 1-1.672 0L2.5 4.31m9.657-.809H3.843L8 7.24l4.157-3.74M1 3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1z" /></svg>);
const MailIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M18.75 6.5H5.25L12 11.563zM4.5 7.813V17.5h15V7.813l-6.6 4.95a1.5 1.5 0 0 1-1.8 0l-6.6-4.95M3 6.5A1.5 1.5 0 0 1 4.5 5h15A1.5 1.5 0 0 1 21 6.5v11a1.5 1.5 0 0 1-1.5 1.5h-15A1.5 1.5 0 0 1 3 17.5z" /></svg>);
const MailIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M25.644 8H6.356L16 15.014zM6 10.214V24h20V10.214l-8.824 6.417a2 2 0 0 1-2.352 0zM4 8a2 2 0 0 1 2-2h20a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2z" /></svg>);

export const MailIcon = createIcon(MailIcon16, MailIcon24, MailIcon32, "MailIcon");