/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import React, { forwardRef, type Ref, type SVGProps } from "react";

const NewTemplateIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" ref={ref} {...props}><path fill="var(--hop-primary-icon)" d="M13 5a2 2 0 1 0 0-4 2 2 0 0 0 0 4" /><path fill="currentColor" fillRule="evenodd" d="M3.498 3.503H9.25a.75.75 0 0 0 0-1.5H3.248c-.69 0-1.25.56-1.25 1.25v9.498c0 .69.56 1.25 1.25 1.25h9.498c.69 0 1.25-.56 1.25-1.25V6.75a.75.75 0 0 0-.74-.75H3.498V3.503M7.5 7.5h4.996v5H7.5zM6 7.5H3.498v5H6z" /></svg>);
const NewTemplateIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M3.996 5.505a1.5 1.5 0 0 1 1.5-1.5h8.756a.75.75 0 0 1 0 1.5H5.496v4.497H18.5V9.75a.75.75 0 0 1 1.5 0v8.758a1.5 1.5 0 0 1-1.5 1.5H5.496a1.5 1.5 0 0 1-1.5-1.5V5.505m1.5 13.004v-7.007H9v7.007zm5.004 0h8v-7.007h-8z" /><path fill="var(--hop-primary-icon)" d="M19 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6" /></svg>);
const NewTemplateIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M8 8v6h16v-.8a1 1 0 1 1 2 0V24a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h10.797a1 1 0 1 1 0 2zm0 16v-8h4v8zm6 0h10v-8H14z" /><path fill="var(--hop-primary-icon)" d="M25 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8" /></svg>);

export const NewTemplateIcon = createIcon(NewTemplateIcon16, NewTemplateIcon24, NewTemplateIcon32, "NewTemplateIcon");