/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import React, { forwardRef, type Ref, type SVGProps } from "react";

const NoteIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M7.999 3.5H3.5v9h9V8.01H9.249c-.69 0-1.25-.56-1.25-1.25V3.5m1.5.406V6.51h2.604zM2 13V3a1 1 0 0 1 1-1h6.3a1 1 0 0 1 .707.293l3.7 3.7A1 1 0 0 1 14 6.7V13a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1" /></svg>);
const NoteIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M5.5 18.5h13v-8.497h-2.994a1.5 1.5 0 0 1-1.5-1.5V5.5H5.5zM15.506 5.628l2.875 2.875h-2.875zM18.5 20h-13A1.5 1.5 0 0 1 4 18.5v-13A1.5 1.5 0 0 1 5.5 4h9.878a1.5 1.5 0 0 1 1.061.44l3.122 3.12A1.5 1.5 0 0 1 20 8.622V18.5a1.5 1.5 0 0 1-1.5 1.5M7.75 15.5a.75.75 0 0 0 0 1.5h8.5a.75.75 0 0 0 0-1.5zM7 12.764a.75.75 0 0 1 .75-.75h8.5a.75.75 0 0 1 0 1.5h-8.5a.75.75 0 0 1-.75-.75M7.75 8.5a.75.75 0 0 0 0 1.5h3.5a.75.75 0 0 0 0-1.5z" /></svg>);
const NoteIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M8 24h16V14h-4a2 2 0 0 1-2-2V8H8zM20 8.828 23.172 12H20zM24 26H8a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h11.172a2 2 0 0 1 1.414.586l4.828 4.828A2 2 0 0 1 26 12.828V24a2 2 0 0 1-2 2m-13.25-6a1 1 0 1 0 0 2h10.5a1 1 0 1 0 0-2zm-1-3a1 1 0 0 1 1-1h10.5a1 1 0 1 1 0 2h-10.5a1 1 0 0 1-1-1m1-5a1 1 0 1 0 0 2H15a1 1 0 1 0 0-2z" /></svg>);

export const NoteIcon = createIcon(NoteIcon16, NoteIcon24, NoteIcon32, "NoteIcon");