/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import React, { forwardRef, type Ref, type SVGProps } from "react";

const PlusIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M8.75 2.75a.75.75 0 1 0-1.5 0v4.5h-4.5a.75.75 0 1 0 0 1.5h4.5v4.501a.75.75 0 0 0 1.5 0V8.75h4.5a.75.75 0 0 0 0-1.5h-4.5z" /></svg>);
const PlusIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M12.75 4.751a.75.75 0 0 0-1.5 0v6.499H4.752a.75.75 0 0 0 0 1.5h6.498v6.498a.75.75 0 0 0 1.5 0V12.75h6.498a.75.75 0 0 0 0-1.5H12.75z" /></svg>);
const PlusIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M18 6a1 1 0 1 0-2 0v9H7a1 1 0 1 0 0 2h9v9a1 1 0 1 0 2 0v-9h9a1 1 0 1 0 0-2h-9z" /></svg>);

export const PlusIcon = createIcon(PlusIcon16, PlusIcon24, PlusIcon32, "PlusIcon");