/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import React, { forwardRef, type Ref, type SVGProps } from "react";

const StarSolidIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M8.897 1.576a1 1 0 0 0-1.794 0l-1.525 3.09-3.41.496a1 1 0 0 0-.555 1.706l2.468 2.405-.583 3.397a1 1 0 0 0 1.451 1.054L8 12.121l3.05 1.603a1 1 0 0 0 1.451-1.054l-.582-3.397 2.468-2.405a1 1 0 0 0-.554-1.706l-3.411-.496-1.525-3.09Z" /></svg>);
const StarSolidIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M13.345 4.03c-.55-1.114-2.14-1.114-2.69 0L8.857 7.675l-4.02.584c-1.23.179-1.722 1.69-.832 2.559l2.91 2.835-.687 4.005c-.21 1.225 1.076 2.16 2.176 1.58L12 17.348l3.596 1.89c1.1.58 2.387-.355 2.176-1.58l-.686-4.005 2.909-2.835c.89-.868.399-2.38-.832-2.559l-4.02-.584-1.798-3.643" /></svg>);
const StarSolidIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M17.793 5.374c-.733-1.486-2.853-1.486-3.586 0l-2.398 4.858-5.36.779c-1.64.238-2.296 2.254-1.109 3.411l3.88 3.781-.917 5.34c-.28 1.633 1.435 2.879 2.902 2.108L16 23.13l4.795 2.52c1.467.772 3.182-.474 2.901-2.108l-.915-5.339 3.879-3.78c1.187-1.158.532-3.174-1.109-3.412l-5.36-.78-2.398-4.857" /></svg>);

export const StarSolidIcon = createIcon(StarSolidIcon16, StarSolidIcon24, StarSolidIcon32, "StarSolidIcon");