/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import React, { forwardRef, type Ref, type SVGProps } from "react";

const SuccessIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M13.5 8a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0M15 8A7 7 0 1 1 1 8a7 7 0 0 1 14 0m-4.43-.636a.75.75 0 1 0-1.06-1.061L7.37 8.441l-.577-.608a.75.75 0 0 0-1.088 1.032l1.107 1.167a.75.75 0 0 0 1.074.014l2.683-2.682" /></svg>);
const SuccessIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M19.5 12a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0m1.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0m-4.455-2.485a.75.75 0 0 0-1.09-1.03l-5.103 5.407-1.793-2.002a.75.75 0 1 0-1.118 1l1.793 2.003a1.5 1.5 0 0 0 2.209.029z" /></svg>);
const SuccessIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M26 16c0 5.523-4.477 10-10 10S6 21.523 6 16 10.477 6 16 6s10 4.477 10 10m2 0c0 6.627-5.373 12-12 12S4 22.627 4 16 9.373 4 16 4s12 5.373 12 12m-5.783-2.802a1 1 0 1 0-1.434-1.396l-7.05 7.245-2.498-2.705a1 1 0 0 0-1.47 1.357l2.498 2.705a2 2 0 0 0 2.903.038l7.05-7.244" /></svg>);

export const SuccessIcon = createIcon(SuccessIcon16, SuccessIcon24, SuccessIcon32, "SuccessIcon");