/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import React, { forwardRef, type Ref, type SVGProps } from "react";

const UnarchiveIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M1 3.254c0-.69.56-1.25 1.25-1.25h11.5c.69 0 1.25.56 1.25 1.25V4.5a1.25 1.25 0 0 1-.999 1.225v7.024c0 .69-.56 1.25-1.25 1.25H3.25c-.69 0-1.25-.56-1.25-1.25V5.725A1.25 1.25 0 0 1 1 4.5zM3.499 5.75H12.5v6.749h-9V5.75ZM13.5 4.25h-11v-.746h11zM8.96 9.357a.75.75 0 1 0 1.061-1.061l-1.49-1.49a.75.75 0 0 0-1.061 0l-1.49 1.49a.75.75 0 0 0 1.06 1.06l.21-.21v1.767a.75.75 0 0 0 1.5 0V9.146l.21.21" /></svg>);
const UnarchiveIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M2.909 5.245c0-.69.56-1.25 1.25-1.25h15.69c.69 0 1.25.56 1.25 1.25v2.226a1.25 1.25 0 0 1-1.089 1.24v10.037c0 .69-.56 1.25-1.25 1.25H5.247c-.69 0-1.25-.56-1.25-1.25V8.711A1.25 1.25 0 0 1 2.91 7.47V5.245m1.5.25v1.726H19.6V5.495H4.409Zm1.088 3.226v9.777H18.51V8.721H5.497m7.995 5.017a.75.75 0 0 0 1.06-1.061l-2.018-2.018a.75.75 0 0 0-1.06 0l-2.019 2.018a.75.75 0 0 0 1.06 1.06l.739-.738v3.034a.75.75 0 0 0 1.5 0V13l.738.739" /></svg>);
const UnarchiveIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M4.643 7.5a1.5 1.5 0 0 1 1.5-1.5h19.714a1.5 1.5 0 0 1 1.5 1.5v3.004a1.5 1.5 0 0 1-1.35 1.492V24.5a1.5 1.5 0 0 1-1.5 1.5H7.493a1.5 1.5 0 0 1-1.5-1.5V11.996a1.5 1.5 0 0 1-1.351-1.492V7.5m2 .5v2.004h18.714V8H6.643Zm1.35 4.004V24h16.013V12.004H7.994Zm9.805 6.206a1 1 0 0 0 1.415-1.415l-2.506-2.505a1 1 0 0 0-1.414 0l-2.505 2.506a1 1 0 1 0 1.414 1.414l.798-.798v3.598a1 1 0 1 0 2 0v-3.598l.798.798" /></svg>);

export const UnarchiveIcon = createIcon(UnarchiveIcon16, UnarchiveIcon24, UnarchiveIcon32, "UnarchiveIcon");