/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import React, { forwardRef, type Ref, type SVGProps } from "react";

const VideoCameraIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M10.5 3.953V3.5h-8v9h8v-1.254a.797.797 0 0 1-.001-.046V4zm1.499 4.76 1.501.875V6.412l-1.501.875zm1.873-4.255L12 5.55V3a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h9a1 1 0 0 0 1-1v-2.55l1.872 1.092A.75.75 0 0 0 15 10.894V5.106a.75.75 0 0 0-1.128-.648" /></svg>);
const VideoCameraIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M20.5 15.175 18 13.222v-2.347L20.5 9zM18 9V6a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h13a1 1 0 0 0 1-1v-2.875l2.384 1.863A1 1 0 0 0 22 16.2V8a1 1 0 0 0-1.6-.8zm-1.5 7V6.5h-12v11h12z" /></svg>);
const VideoCameraIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="m27 20.263-4-2.667v-3.192l4-2.667zM23 12l4.445-2.964A1 1 0 0 1 29 9.87v12.263a1 1 0 0 1-1.555.831L23 20v4a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h15a2 2 0 0 1 2 2zm-2 0V8H6v16h15v-8.263z" /></svg>);

export const VideoCameraIcon = createIcon(VideoCameraIcon16, VideoCameraIcon24, VideoCameraIcon32, "VideoCameraIcon");