import fs from "fs";
import type { MultiSourceIconSource } from "./fetchSvgs.ts";

const GENERATED_HEADER = `/*
* This file is generated by the generate-components script. Do not edit directly.
*/\n
/* eslint-disable */`;

export const generateIndex = (componentDirectory: string, iconsByNames: MultiSourceIconSource[]) => {
    const iconList = iconsByNames.map(icon => icon.name + "Icon");
    const indexFile = `${componentDirectory}/index.ts`;
    const indexContent = `${GENERATED_HEADER}\n
${Object.values(iconsByNames).map(icon => `export * from "./${icon.name}Icon.tsx";`).join("\n")}
\nexport const iconNames = ${JSON.stringify(iconList)} as const;`;

    fs.writeFileSync(indexFile, indexContent);
};
