/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const AlignmentIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M13.5 8a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0M15 8A7 7 0 1 1 1 8a7 7 0 0 1 14 0m-4.82-3.577a1.188 1.188 0 0 1 1.396 1.398l-.804 4.02c-.094.47-.461.838-.931.932l-4.02.804a1.188 1.188 0 0 1-1.398-1.397l.804-4.02c.094-.471.462-.838.932-.932zm-.166 1.563-3.357.672-.67 3.356 3.355-.671zM8.875 8a.875.875 0 1 1-1.75 0 .875.875 0 0 1 1.75 0" /></svg>);
const AlignmentIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M12 19.5a7.5 7.5 0 1 0 0-15 7.5 7.5 0 0 0 0 15m0 1.5a9 9 0 1 0 0-18 9 9 0 0 0 0 18m2.838-13.381a1.31 1.31 0 0 1 1.543 1.543l-1.032 5.158c-.104.52-.51.925-1.029 1.029L9.162 16.38a1.31 1.31 0 0 1-1.543-1.543l1.032-5.159A1.31 1.31 0 0 1 9.679 8.65zm.016 1.526-4.757.952-.951 4.757 4.757-.951zM12 13.122a1.123 1.123 0 1 0 0-2.245 1.123 1.123 0 0 0 0 2.245" /></svg>);
const AlignmentIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M16 26c5.523 0 10-4.477 10-10S21.523 6 16 6 6 10.477 6 16s4.477 10 10 10m0 2c6.627 0 12-5.373 12-12S22.627 4 16 4 4 9.373 4 16s5.373 12 12 12m4.151-18.29a1.818 1.818 0 0 1 2.139 2.139l-1.503 7.513a1.82 1.82 0 0 1-1.425 1.425l-7.513 1.503a1.818 1.818 0 0 1-2.139-2.138l1.503-7.513a1.82 1.82 0 0 1 1.425-1.426zm.124 2.015L13.15 13.15l-1.425 7.126 7.125-1.426zM16 17.385a1.386 1.386 0 1 0 0-2.77 1.386 1.386 0 0 0 0 2.77" /></svg>);

export const AlignmentIcon = createIcon(AlignmentIcon16, AlignmentIcon24, AlignmentIcon32, "AlignmentIcon");