/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const AngleDownIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M14.03 5.575a.75.75 0 0 0-1.06 0L8 10.544l-4.97-4.97a.75.75 0 1 0-1.06 1.061l5.323 5.323a1 1 0 0 0 1.414 0l5.323-5.323a.75.75 0 0 0 0-1.06" /></svg>);
const AngleDownIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M20.785 8.57a.75.75 0 0 0-1.06 0L12 16.296 4.276 8.571a.75.75 0 0 0-1.061 1.06l8.078 8.078a1 1 0 0 0 1.414 0l8.078-8.078a.75.75 0 0 0 0-1.06" /></svg>);
const AngleDownIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M27.707 11.397a1 1 0 0 0-1.414 0L16 21.69 5.707 11.397a1 1 0 0 0-1.414 1.414l10.823 10.823a1.25 1.25 0 0 0 1.768 0l10.823-10.823a1 1 0 0 0 0-1.414" /></svg>);

export const AngleDownIcon = createIcon(AngleDownIcon16, AngleDownIcon24, AngleDownIcon32, "AngleDownIcon");