/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const AngleUpIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M1.97 10.43a.75.75 0 0 0 1.06 0L8 5.46l4.97 4.97a.75.75 0 1 0 1.06-1.061L8.707 4.046a1 1 0 0 0-1.414 0L1.97 9.37a.75.75 0 0 0 0 1.06" /></svg>);
const AngleUpIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M3.215 15.425a.75.75 0 0 0 1.06 0L12 7.701l7.724 7.724a.75.75 0 0 0 1.061-1.06l-8.078-8.079a1 1 0 0 0-1.414 0l-8.078 8.078a.75.75 0 0 0 0 1.061" /></svg>);
const AngleUpIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M4.293 20.607a1 1 0 0 0 1.414 0L16 10.314l10.293 10.293a1 1 0 0 0 1.414-1.414L16.884 8.37a1.25 1.25 0 0 0-1.768 0L4.293 19.193a1 1 0 0 0 0 1.414" /></svg>);

export const AngleUpIcon = createIcon(AngleUpIcon16, AngleUpIcon24, AngleUpIcon32, "AngleUpIcon");