/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const AngleLeftIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M10.53 13.775a.75.75 0 0 0 0-1.06l-4.97-4.97 4.97-4.969a.75.75 0 1 0-1.061-1.06L4.146 7.038a1 1 0 0 0 0 1.414l5.323 5.323a.75.75 0 0 0 1.06 0" /></svg>);
const AngleLeftIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M15.425 20.785a.75.75 0 0 0 0-1.06L7.701 12l7.724-7.725a.75.75 0 1 0-1.06-1.06l-8.079 8.078a1 1 0 0 0 0 1.414l8.078 8.078a.75.75 0 0 0 1.061 0" /></svg>);
const AngleLeftIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M20.597 27.707a1 1 0 0 0 0-1.414L10.304 16 20.597 5.707a1 1 0 0 0-1.414-1.414L8.36 15.116a1.25 1.25 0 0 0 0 1.768l10.823 10.823a1 1 0 0 0 1.414 0" /></svg>);

export const AngleLeftIcon = createIcon(AngleLeftIcon16, AngleLeftIcon24, AngleLeftIcon32, "AngleLeftIcon");