/*** This file is generated by the generate-components script. Do not edit directly.*/
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";
const ArrowUpIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M7.468 1.229 2.363 6.333a.75.75 0 0 0 1.061 1.061l3.832-3.832v10.696a.75.75 0 0 0 1.5 0V3.562l3.832 3.832a.75.75 0 0 0 1.06-1.06L8.538 1.22a.75.75 0 0 0-1.069.008" /></svg>);
const ArrowUpIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M18.782 10.534a.75.75 0 0 0 0-1.06L12.529 3.22a.749.749 0 0 0-1.06 0L5.216 9.474a.75.75 0 1 0 1.06 1.06l4.973-4.971V20.25a.75.75 0 0 0 1.5 0V5.56l4.972 4.973a.75.75 0 0 0 1.061 0" /></svg>);
const ArrowUpIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M25.73 14.73a1 1 0 0 0-.001-1.415l-9.008-9.008a.996.996 0 0 0-1.434.004l-9.003 9.004a1 1 0 0 0 1.414 1.414l7.321-7.321V27.02a1 1 0 1 0 2 0V7.434l7.296 7.295a1 1 0 0 0 1.414 0" /></svg>);

export const ArrowUpIcon = createIcon(ArrowUpIcon16, ArrowUpIcon24, ArrowUpIcon32, "ArrowUpIcon");