/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const AssistantIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M5.5 4.75a.75.75 0 0 1 .75.75v5.833c0 .348.086.627.186.793a.5.5 0 0 0 .098.124H8a.75.75 0 0 1 0 1.5H6.5c-.643 0-1.097-.43-1.35-.852-.262-.437-.4-.992-.4-1.565V5.5a.75.75 0 0 1 .75-.75m1.048 7.509-.006-.003z" /><path fillRule="evenodd" d="M3.5 2.5v2h4v-2zM3 1a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z" /><path d="M8 12a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H9a1 1 0 0 1-1-1z" /></svg>);
const AssistantIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M9 8.75a.75.75 0 0 1 .75.75v7c0 .855.528 1.25.85 1.25H13a.75.75 0 0 1 0 1.5h-2.4c-1.445 0-2.35-1.396-2.35-2.75v-7A.75.75 0 0 1 9 8.75" /><path fillRule="evenodd" d="M6.5 4.5v4h5v-4zM6 3a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1z" /><path d="M12 17a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-5a1 1 0 0 1-1-1z" /></svg>);
const AssistantIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M12 11a1 1 0 0 1 1 1v9.722c0 .624.148 1.14.335 1.465.147.256.256.305.279.313H16a1 1 0 1 1 0 2h-2.4c-.951 0-1.622-.661-1.998-1.314-.392-.68-.602-1.554-.602-2.464V12a1 1 0 0 1 1-1" /><path d="M16 22a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1h-8a1 1 0 0 1-1-1z" /><path fillRule="evenodd" d="M8 6v5h8V6zM7 4a1 1 0 0 0-1 1v7a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1z" /></svg>);

export const AssistantIcon = createIcon(AssistantIcon16, AssistantIcon24, AssistantIcon32, "AssistantIcon");