/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const AssistantToIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M4.25 11.5V4h1.5v7.5c0 .138.112.25.25.25h2v1.5H6a1.75 1.75 0 0 1-1.75-1.75" /><path fillRule="evenodd" d="M8.5 11.5v2h4v-2zM8 10a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h5a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1z" /><path d="M2 2a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1z" /></svg>);
const AssistantToIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M7.75 16.5v-9h1.5v9c0 .138.112.25.25.25h2v1.5h-2a1.75 1.75 0 0 1-1.75-1.75" /><path fillRule="evenodd" d="M12.5 15.5v4h5v-4zM12 14a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-5a1 1 0 0 0-1-1z" /><path d="M5 4a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1z" /></svg>);
const AssistantToIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path d="M6 5a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1z" /><path fillRule="evenodd" d="M10 23V10h2v13h4v2h-4a2 2 0 0 1-2-2" /><path fillRule="evenodd" d="M16 21v5h8v-5zm-1-2a1 1 0 0 0-1 1v7a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1v-7a1 1 0 0 0-1-1z" /></svg>);

export const AssistantToIcon = createIcon(AssistantToIcon16, AssistantToIcon24, AssistantToIcon32, "AssistantToIcon");