/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const AttachmentIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M8.37 2.966a3.298 3.298 0 1 1 4.664 4.664L7.63 13.034A3.298 3.298 0 0 1 2.966 8.37l2.577-2.577A2.085 2.085 0 0 1 8.491 8.74l-1.513 1.513a.75.75 0 1 1-1.06-1.06L7.43 7.68a.585.585 0 0 0-.827-.826L4.027 9.43a1.798 1.798 0 0 0 2.542 2.542l5.405-5.404A1.798 1.798 0 0 0 9.43 4.026l-.246.246a.75.75 0 1 1-1.06-1.06z" /></svg>);
const AttachmentIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M12.714 5.25a4.268 4.268 0 1 1 6.036 6.036l-7.464 7.464a4.268 4.268 0 1 1-6.036-6.036l3.48-3.48a2.705 2.705 0 0 1 3.826 3.824l-2.01 2.01a.75.75 0 1 1-1.062-1.06l2.01-2.01a1.205 1.205 0 0 0-1.703-1.704l-3.48 3.48a2.768 2.768 0 0 0 3.915 3.915l7.463-7.463a2.768 2.768 0 1 0-3.915-3.915l-.339.34a.75.75 0 0 1-1.06-1.062z" /></svg>);
const AttachmentIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M16.692 7.597a5.452 5.452 0 1 1 7.711 7.71l-9.095 9.096a5.452 5.452 0 1 1-7.711-7.71l4.198-4.199a3.474 3.474 0 0 1 4.912 4.913l-2.449 2.448a1 1 0 0 1-1.414-1.414l2.449-2.448a1.474 1.474 0 0 0-2.084-2.085l-4.198 4.198a3.452 3.452 0 0 0 4.883 4.883l9.095-9.095a3.452 3.452 0 1 0-4.883-4.883l-.35.35a1 1 0 1 1-1.414-1.414z" /></svg>);

export const AttachmentIcon = createIcon(AttachmentIcon16, AttachmentIcon24, AttachmentIcon32, "AttachmentIcon");