/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const BoltIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M9.32 1.04a.75.75 0 0 1 .508.71v4.494h2.698a.75.75 0 0 1 .593 1.208l-5.603 7.256a.75.75 0 0 1-1.343-.458v-4.5H3.474a.75.75 0 0 1-.593-1.208l5.603-7.25a.75.75 0 0 1 .836-.251M5.002 8.25h1.92a.75.75 0 0 1 .75.75v3.051L11 7.744H9.078a.75.75 0 0 1-.75-.75V3.947z" /></svg>);
const BoltIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M13.665 3.04a.75.75 0 0 1 .508.71v6.17h3.801a.75.75 0 0 1 .594 1.209l-7.397 9.579a.75.75 0 0 1-1.343-.459v-6.18H6.026a.75.75 0 0 1-.594-1.208l7.397-9.57a.75.75 0 0 1 .836-.252m-6.112 9.53h3.025a.75.75 0 0 1 .75.75v4.732l5.12-6.63h-3.026a.75.75 0 0 1-.75-.75V5.946z" /></svg>);
const BoltIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M18.307 4.054a1 1 0 0 1 .675.946v8.229h4.983a1 1 0 0 1 .79 1.614L14.82 27.614A1 1 0 0 1 13.03 27v-8.24H8.034a1 1 0 0 1-.788-1.614l9.947-12.76a1 1 0 0 1 1.114-.332m-8.225 12.707h3.948a1 1 0 0 1 1 1v6.325l6.89-8.857h-3.938a1 1 0 0 1-1-1v-6.32z" /></svg>);

export const BoltIcon = createIcon(BoltIcon16, BoltIcon24, BoltIcon32, "BoltIcon");