/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const BookIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M13.356 1.257A1.25 1.25 0 0 1 15 2.443v9.78a1.25 1.25 0 0 1-.855 1.187l-4.659 1.553A.8.8 0 0 1 9.25 15h-2.5a.8.8 0 0 1-.237-.038l-4.66-1.553A1.25 1.25 0 0 1 1 12.224V2.443a1.25 1.25 0 0 1 1.645-1.186l4.227 1.409H9.13zM8.5 4.166h-1v9.335h1zm1.5 9.045 3.501-1.167V2.79l-3.5 1.167zm-4 0V3.957L2.499 2.79v9.254z" /></svg>);
const BookIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M3.005 4.795a1.5 1.5 0 0 1 1.974-1.423l5.494 1.832h3.054l5.494-1.832a1.5 1.5 0 0 1 1.974 1.423v12.71a1.5 1.5 0 0 1-1.026 1.424l-6.083 2.028a.8.8 0 0 1-.237.038h-3.298a.8.8 0 0 1-.237-.038L4.03 18.929a1.5 1.5 0 0 1-1.026-1.423zm9.894 1.909h-1.798v12.791h1.798zm1.5 12.5 5.096-1.698V4.796L14.4 6.493zm-4.798 0V6.494L4.505 4.795v12.71z" /></svg>);
const BookIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M25.368 4.49A2 2 0 0 1 28 6.387v16.959a2 2 0 0 1-1.367 1.897l-8.117 2.706A1 1 0 0 1 18.2 28h-4.4a1 1 0 0 1-.316-.051l-8.116-2.706A2 2 0 0 1 4 23.346V6.387A2 2 0 0 1 6.632 4.49l7.33 2.443h4.076zM17.2 8.933h-2.4V26h2.4zm2 16.68 6.8-2.267V6.387l-6.8 2.267zm-6.4 0V8.654L6 6.387v16.959z" /></svg>);

export const BookIcon = createIcon(BookIcon16, BookIcon24, BookIcon32, "BookIcon");