/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const BookmarkIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M12.142 14.836a1.25 1.25 0 0 0 1.862-1.09V2.25c0-.69-.56-1.25-1.25-1.25H3.246c-.69 0-1.25.56-1.25 1.25v11.496a1.25 1.25 0 0 0 1.862 1.09L8 12.51zm.362-1.518-3.892-2.184a1.25 1.25 0 0 0-1.224 0l-3.892 2.184V2.5h9.008z" /></svg>);
const BookmarkIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M17.5 4.5v14.584l-3.943-2.394a3 3 0 0 0-3.114 0L6.5 19.084l.778 1.283 3.944-2.394a1.5 1.5 0 0 1 1.556 0l3.943 2.394A1.5 1.5 0 0 0 19 19.084V4.5A1.5 1.5 0 0 0 17.5 3h-11A1.5 1.5 0 0 0 5 4.5v14.584a1.5 1.5 0 0 0 2.278 1.283L6.5 19.084V4.5z" /></svg>);
const BookmarkIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M6 25.217c0 1.562 1.71 2.52 3.043 1.707L16 22.672l6.957 4.252c1.333.814 3.043-.145 3.043-1.707V6a2 2 0 0 0-2-2H8a2 2 0 0 0-2 2zm8.957-4.252L8 25.217V6h16v19.217l-6.957-4.252a2 2 0 0 0-2.086 0" /></svg>);

export const BookmarkIcon = createIcon(BookmarkIcon16, BookmarkIcon24, BookmarkIcon32, "BookmarkIcon");