/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const BriefcaseIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M5.5 2a1 1 0 0 0-1 1v1.5H2a1 1 0 0 0-1 1V13a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V5.5a1 1 0 0 0-1-1h-2.5V3a1 1 0 0 0-1-1zM10 4.5v-1H6v1zm-7.5 8V6h11v6.5z" /></svg>);
const BriefcaseIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M9.25 5C8.56 5 8 5.56 8 6.25V8H4.5A1.5 1.5 0 0 0 3 9.5v8A1.5 1.5 0 0 0 4.5 19h15a1.5 1.5 0 0 0 1.5-1.5v-8A1.5 1.5 0 0 0 19.5 8H16V6.25C16 5.56 15.44 5 14.75 5zm5.25 3V6.5h-5V8zm-10 1.5h15v8h-15z" /></svg>);
const BriefcaseIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M12 6a1.5 1.5 0 0 0-1.5 1.5v3H6a2 2 0 0 0-2 2V24a2 2 0 0 0 2 2h20a2 2 0 0 0 2-2V12.5a2 2 0 0 0-2-2h-4.5v-3A1.5 1.5 0 0 0 20 6zm7.5 4.5V8h-7v2.5zM6 12.5h20V24H6z" /></svg>);

export const BriefcaseIcon = createIcon(BriefcaseIcon16, BriefcaseIcon24, BriefcaseIcon32, "BriefcaseIcon");