/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const CaretUpSolidIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M10.793 10.75c1.114 0 1.671-1.346.884-2.134L8.884 5.823l-.53.53.53-.53a1.25 1.25 0 0 0-1.768 0L4.323 8.616c-.787.788-.23 2.134.884 2.134z" /></svg>);
const CaretUpSolidIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="m5.23 12.37 5.71-5.71a1.5 1.5 0 0 1 2.12 0l5.71 5.71c.945.944.276 2.56-1.06 2.56H6.29c-1.336 0-2.006-1.616-1.06-2.56" /></svg>);
const CaretUpSolidIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="m8.008 16.591 6.578-6.577a2 2 0 0 1 2.828 0l6.577 6.577c1.26 1.26.368 3.415-1.414 3.415H9.423c-1.782 0-2.675-2.155-1.415-3.415" /></svg>);

export const CaretUpSolidIcon = createIcon(CaretUpSolidIcon16, CaretUpSolidIcon24, CaretUpSolidIcon32, "CaretUpSolidIcon");