/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const CaretDownSolidIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M5.207 5.25c-1.114 0-1.671 1.346-.884 2.134l2.793 2.793a1.25 1.25 0 0 0 1.768 0l2.793-2.793c.787-.788.23-2.134-.884-2.134z" /></svg>);
const CaretDownSolidIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="m18.77 11.58-5.71 5.71a1.5 1.5 0 0 1-2.12 0l-5.71-5.71c-.946-.946-.276-2.561 1.06-2.561h11.42c1.336 0 2.005 1.615 1.06 2.56" /></svg>);
const CaretDownSolidIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="m23.992 15.417-6.578 6.577a2 2 0 0 1-2.828 0l-6.578-6.577c-1.26-1.26-.367-3.415 1.415-3.415h13.154c1.782 0 2.674 2.155 1.415 3.415" /></svg>);

export const CaretDownSolidIcon = createIcon(CaretDownSolidIcon16, CaretDownSolidIcon24, CaretDownSolidIcon32, "CaretDownSolidIcon");