/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const ChartLineIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M3.505 2.759a.75.75 0 1 0-1.5 0v10.495c0 .414.336.75.75.75H13.25a.75.75 0 1 0 0-1.5H3.505V2.759Zm9.109 4.028a.75.75 0 1 0-1.06-1.06L9.75 7.528 8.533 6.31a.75.75 0 0 0-1.061 0L5.14 8.642a.75.75 0 0 0 1.06 1.06l1.802-1.801 1.219 1.218a.75.75 0 0 0 1.06 0l2.333-2.332" /></svg>);
const ChartLineIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M5.5 4.75a.75.75 0 0 0-1.5 0V19a1 1 0 0 0 1 1h14.25a.75.75 0 0 0 0-1.5H5.5zm12.78 5.03a.75.75 0 0 0-1.06-1.06l-3.47 3.47-1.116-1.117a1.25 1.25 0 0 0-1.768 0L8.22 13.72a.75.75 0 1 0 1.06 1.06l2.47-2.47 1.116 1.117a1.25 1.25 0 0 0 1.768 0z" /></svg>);
const ChartLineIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M8 7a1 1 0 0 0-2 0v18a1 1 0 0 0 1 1h18a1 1 0 1 0 0-2H8zm15.707 6.707a1 1 0 0 0-1.414-1.414L18 16.586l-2.293-2.293a1 1 0 0 0-1.414 0l-4 4a1 1 0 1 0 1.414 1.414L15 16.414l2.293 2.293a1 1 0 0 0 1.414 0z" /></svg>);

export const ChartLineIcon = createIcon(ChartLineIcon16, ChartLineIcon24, ChartLineIcon32, "ChartLineIcon");