/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const ChartBarIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M3.503 2.758a.75.75 0 0 0-1.5 0v10.497c0 .415.336.75.75.75H13.25a.75.75 0 0 0 0-1.5H3.503V2.758ZM9.5 4.25a.75.75 0 0 0-1.5 0v6a.75.75 0 0 0 1.5 0zm-3 2a.75.75 0 0 0-1.5 0v4a.75.75 0 0 0 1.5 0zm5.25 1.25a.75.75 0 0 1 .75.75v2a.75.75 0 0 1-1.5 0v-2a.75.75 0 0 1 .75-.75" /></svg>);
const ChartBarIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M5.5 4.75a.75.75 0 0 0-1.5 0v14c0 .69.56 1.25 1.25 1.25h14a.75.75 0 0 0 0-1.5H5.5zm4 4.5a.75.75 0 0 0-1.5 0v7a.75.75 0 0 0 1.5 0zM12.75 5a.75.75 0 0 1 .75.75v10.5a.75.75 0 0 1-1.5 0V5.75a.75.75 0 0 1 .75-.75m4.75 6.75a.75.75 0 0 0-1.5 0v4.5a.75.75 0 0 0 1.5 0z" /></svg>);
const ChartBarIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M8 7a1 1 0 0 0-2 0v18a1 1 0 0 0 1 1h18a1 1 0 1 0 0-2H8zm5 6a1 1 0 1 0-2 0v8a1 1 0 1 0 2 0zm4-5a1 1 0 0 1 1 1v12a1 1 0 1 1-2 0V9a1 1 0 0 1 1-1m6 7a1 1 0 1 0-2 0v6a1 1 0 1 0 2 0z" /></svg>);

export const ChartBarIcon = createIcon(ChartBarIcon16, ChartBarIcon24, ChartBarIcon32, "ChartBarIcon");