/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const CommentIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M8 2.504a5.5 5.5 0 0 0 0 11h5.047l-.864-.865a.75.75 0 0 1-.035-1.023A5.5 5.5 0 0 0 8 2.504m-7 5.5a7 7 0 1 1 12.714 4.045l1.674 1.674a.75.75 0 0 1-.53 1.28H8a7 7 0 0 1-7-7" /></svg>);
const CommentIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M11.948 4.5a7.5 7.5 0 0 0 0 15h7.241l-1.55-1.551a.75.75 0 0 1-.036-1.023A7.5 7.5 0 0 0 11.947 4.5m-9 7.5a9 9 0 1 1 16.227 5.364l2.355 2.356A.75.75 0 0 1 21 21h-9.052a9 9 0 0 1-9-9" /></svg>);
const CommentIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M16 6C10.477 6 6 10.477 6 16s4.477 10 10 10h9.656l-2.068-2.068a1 1 0 0 1-.047-1.364A9.957 9.957 0 0 0 26 16c0-5.523-4.477-10-10-10M4 16C4 9.373 9.373 4 16 4s12 5.373 12 12c0 2.68-.88 5.155-2.363 7.152l3.14 3.14A1 1 0 0 1 28.07 28H16C9.373 28 4 22.627 4 16" /></svg>);

export const CommentIcon = createIcon(CommentIcon16, CommentIcon24, CommentIcon32, "CommentIcon");