/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const ConnectionsIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M5.084 10.916A5.001 5.001 0 0 1 6 1a5 5 0 0 1 4.916 4.084A5.002 5.002 0 0 1 10 15a5 5 0 0 1-4.916-4.084m-.044-1.55A5 5 0 0 1 9.367 5.04 3.502 3.502 0 0 0 2.5 6c0 1.6 1.074 2.95 2.54 3.367m1.593 1.594A3.502 3.502 0 0 0 13.5 10c0-1.6-1.074-2.95-2.54-3.367a5 5 0 0 1-4.327 4.327m2.825-4.418a3.5 3.5 0 0 0-2.916 2.916 3.5 3.5 0 0 0 2.916-2.916" /></svg>);
const ConnectionsIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M15.743 8.257a6 6 0 1 0-7.486 7.486 6 6 0 1 0 7.486-7.486M14.5 10a4.5 4.5 0 0 1-4.975 4.475 4.5 4.5 0 0 1 4.95-4.95q.025.235.025.475m-.468-2H14a6 6 0 0 0-6 6.032A4.5 4.5 0 1 1 14.032 8M16 9.968V10a6 6 0 0 1-6 6h-.032A4.5 4.5 0 1 0 16 9.968" /></svg>);
const ConnectionsIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M20.797 11.203a8 8 0 1 0-9.595 9.595 8 8 0 1 0 9.595-9.595M13 19a6 6 0 0 0 6-6 6 6 0 0 0-6 6m5.661-7.993a8 8 0 0 0-7.654 7.654 6 6 0 1 1 7.654-7.654m2.332 2.332a8 8 0 0 1-7.654 7.654 6 6 0 1 0 7.654-7.654" /></svg>);

export const ConnectionsIcon = createIcon(ConnectionsIcon16, ConnectionsIcon24, ConnectionsIcon32, "ConnectionsIcon");