/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const DeleteIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M6.008 2.5V3h3.984v-.5zm-.5-1.5a1 1 0 0 0-1 1v1H1.75a.75.75 0 0 0 0 1.5H2V14a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V4.5h.24a.75.75 0 0 0 0-1.5h-2.748V2a1 1 0 0 0-1-1zM12.5 4.5h-9v9h9zM6.263 6.503a.75.75 0 0 1 .75.75v3.576a.75.75 0 0 1-1.5 0V7.253a.75.75 0 0 1 .75-.75m4.325.75a.75.75 0 0 0-1.5 0v3.576a.75.75 0 0 0 1.5 0z" /></svg>);
const DeleteIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M14 4.5h-4a.5.5 0 0 0-.5.5v1h5V5a.5.5 0 0 0-.5-.5M16 6V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v1H4.75a.75.75 0 0 0 0 1.5H5v12A1.5 1.5 0 0 0 6.5 21h11a1.5 1.5 0 0 0 1.5-1.5v-12h.25a.75.75 0 0 0 0-1.5zm1.5 1.5h-11v12h11zM9.75 10a.75.75 0 0 1 .75.75v5.5a.75.75 0 0 1-1.5 0v-5.5a.75.75 0 0 1 .75-.75m5.25.75a.75.75 0 0 0-1.5 0v5.5a.75.75 0 0 0 1.5 0z" /></svg>);
const DeleteIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M19.333 6h-6.666v2h6.666zm2 2V6a2 2 0 0 0-2-2h-6.666a2 2 0 0 0-2 2v2H5a1 1 0 0 0 0 2h1v16a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V10h1a1 1 0 1 0 0-2zM24 10H8v16h16zm-10 4a1 1 0 1 0-2 0v8a1 1 0 1 0 2 0zm5-1a1 1 0 0 1 1 1v8a1 1 0 1 1-2 0v-8a1 1 0 0 1 1-1" /></svg>);

export const DeleteIcon = createIcon(DeleteIcon16, DeleteIcon24, DeleteIcon32, "DeleteIcon");