/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const DepartmentIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M7.25 8.5v-4h1.5v4z" /><path d="M3 3a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z" /><path fillRule="evenodd" d="M2.5 11.5v1h3v-1zM2 10a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h4a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1zm8.5 1.5v1h3v-1zM10 10a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h4a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1zM3.25 9c0-.966.784-1.75 1.75-1.75h6c.966 0 1.75.784 1.75 1.75v1h-1.5V9a.25.25 0 0 0-.25-.25H5a.25.25 0 0 0-.25.25v1h-1.5z" /></svg>);
const DepartmentIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M11.25 12.75v-3h1.5v3z" /><path d="M5 6a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1z" /><path fillRule="evenodd" d="M4.5 15.5v2h5v-2zM4 14a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1zm10.5 1.5v2h5v-2zM14 14a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1zm-8.25-1c0-.966.784-1.75 1.75-1.75h9c.966 0 1.75.784 1.75 1.75v1h-1.5v-1a.25.25 0 0 0-.25-.25h-9a.25.25 0 0 0-.25.25v1h-1.5z" /></svg>);
const DepartmentIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M15 17V9h2v8z" /><path fillRule="evenodd" d="M8.5 17a2 2 0 0 1 2-2h11a2 2 0 0 1 2 2v3h-2v-3h-11v3h-2z" /><path d="M8 7a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1H9a1 1 0 0 1-1-1z" /><path fillRule="evenodd" d="M6 21v3h7v-3zm-1-2a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h9a1 1 0 0 0 1-1v-5a1 1 0 0 0-1-1zm14 2v3h7v-3zm-1-2a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h9a1 1 0 0 0 1-1v-5a1 1 0 0 0-1-1z" /></svg>);

export const DepartmentIcon = createIcon(DepartmentIcon16, DepartmentIcon24, DepartmentIcon32, "DepartmentIcon");