/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const DottedLinesIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M1 11.333V13a1 1 0 0 0 1 1h1.333v-1.5H2.5v-1.167zM3.333 2H2a1 1 0 0 0-1 1v1.667h1.5V3.5h.833zM1 9.667h1.5V6.333H1zM4.667 2v1.5h2.666V2zm4 0v1.5h2.666V2zm4 0v1.5h.833v1.167H15V3a1 1 0 0 0-1-1zM15 6.333h-1.5v3.334H15zm0 5h-1.5V12.5h-.833V14H14a1 1 0 0 0 1-1zM11.333 14v-1.5H8.667V14zm-4 0v-1.5H4.667V14z" /></svg>);
const DottedLinesIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M3 16.667V18a1 1 0 0 0 1 1h1.333v-1.5H4.5v-.833zM5.333 5H4a1 1 0 0 0-1 1v1.333h1.5V6.5h.833zM3 15.333h1.5v-2.666H3zm0-4h1.5V8.667H3zM6.667 5v1.5h2.666V5zm4 0v1.5h2.666V5zm4 0v1.5h2.666V5zm4 0v1.5h.833v.833H21V6a1 1 0 0 0-1-1zM21 8.667h-1.5v2.666H21zm0 4h-1.5v2.666H21zm0 4h-1.5v.833h-.833V19H20a1 1 0 0 0 1-1zM17.333 19v-1.5h-2.666V19zm-4 0v-1.5h-2.666V19zm-4 0v-1.5H6.667V19z" /></svg>);
const DottedLinesIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M4 23.65V25a1 1 0 0 0 1 1h1.65v-2H6v-.35zm0-1.8h2v-2.7H4zm0-4.5h2v-2.7H4zm0-4.5h2v-2.7H4zm0-4.5h2V8h.65V6H5a1 1 0 0 0-1 1zM8.85 6v2h3.3V6zm5.5 0v2h3.3V6zm5.5 0v2h3.3V6zm5.5 0v2H26v.35h2V7a1 1 0 0 0-1-1zM28 10.15h-2v2.7h2zm0 4.5h-2v2.7h2zm0 4.5h-2v2.7h2zm0 4.5h-2V24h-.65v2H27a1 1 0 0 0 1-1zM23.15 26v-2h-3.3v2zm-5.5 0v-2h-3.3v2zm-5.5 0v-2h-3.3v2z" /></svg>);

export const DottedLinesIcon = createIcon(DottedLinesIcon16, DottedLinesIcon24, DottedLinesIcon32, "DottedLinesIcon");