/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const DownloadIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M8 .99a.75.75 0 0 1 .75.75v7.32l1.56-1.559a.75.75 0 0 1 1.06 1.06l-2.604 2.605a1.083 1.083 0 0 1-1.532 0L4.63 8.562A.75.75 0 0 1 5.69 7.5l1.56 1.56V1.74A.75.75 0 0 1 8 .99M3.5 11.4v2.091h9v-2.09a.75.75 0 0 1 1.5 0v2.34c0 .69-.56 1.25-1.25 1.25h-9.5c-.69 0-1.25-.56-1.25-1.25v-2.34a.75.75 0 0 1 1.5 0" /></svg>);
const DownloadIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M12 3a.75.75 0 0 1 .75.75v9.842l2.344-2.344a.75.75 0 1 1 1.06 1.06l-3.388 3.39a1.083 1.083 0 0 1-1.532 0l-3.389-3.39a.75.75 0 1 1 1.061-1.06l2.344 2.344V3.75A.75.75 0 0 1 12 3M5 19.51a1.5 1.5 0 0 0 1.5 1.5h11a1.5 1.5 0 0 0 1.5-1.5V17a.75.75 0 0 0-1.5 0v2.51h-11V17A.75.75 0 0 0 5 17z" /></svg>);
const DownloadIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M16 4a1 1 0 0 1 1 1v13.366l3.512-3.512a1 1 0 0 1 1.414 1.414l-4.983 4.984c-.52.52-1.365.52-1.886 0l-4.983-4.984a1 1 0 0 1 1.414-1.414L15 18.366V5a1 1 0 0 1 1-1M6 26a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-4a1 1 0 1 0-2 0v4H8v-4a1 1 0 1 0-2 0z" /></svg>);

export const DownloadIcon = createIcon(DownloadIcon16, DownloadIcon24, DownloadIcon32, "DownloadIcon");