/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const EditIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M11.48 2.364a1.25 1.25 0 0 0-1.768 0L3.198 8.878a.75.75 0 0 0-.176.278l-.027.076-.947 3.164a1.25 1.25 0 0 0 1.556 1.556l3.164-.946a1 1 0 0 0 .089-.033.75.75 0 0 0 .265-.171l6.514-6.514a1.25 1.25 0 0 0 0-1.768zM4.79 9.408l5.806-5.807L12.4 5.404 6.592 11.21zm.344 2.52-1.516.454.454-1.516z" /></svg>);
const EditIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M16.651 4.446a1.5 1.5 0 0 0-2.121 0L5.556 13.42a.75.75 0 0 0-.177.282 1 1 0 0 0-.033.088l-1.279 4.276c-.342 1.143.724 2.209 1.867 1.867l4.276-1.28a1 1 0 0 0 .096-.035.75.75 0 0 0 .273-.175l8.974-8.974a1.5 1.5 0 0 0 0-2.12zM7.147 13.95l8.444-8.443 2.902 2.902-8.444 8.443zm-1.643 4.546.92-3.072 2.152 2.153z" /></svg>);
const EditIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M22.464 5.805a2 2 0 0 0-2.828 0L8.003 17.438a1 1 0 0 0-.237.375q-.024.056-.042.116l-1.647 5.505c-.456 1.524.965 2.945 2.49 2.49l5.505-1.647a1 1 0 0 0 .128-.049 1 1 0 0 0 .362-.231l11.633-11.633a2 2 0 0 0 0-2.829zM21.05 7.219l3.73 3.73-10.925 10.926-3.73-3.73zM9.16 20.107l2.733 2.734-3.9 1.166z" /></svg>);

export const EditIcon = createIcon(EditIcon16, EditIcon24, EditIcon32, "EditIcon");