/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const EnterIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path d="M15 14a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-2.25a.75.75 0 0 1 1.5 0v1.75h8v-11h-8v1.75a.75.75 0 0 1-1.5 0V2a1 1 0 0 1 1-1h9a1 1 0 0 1 1 1z" /><path d="M8.22 5.22a.75.75 0 0 1 1.06 0l2.25 2.25a.75.75 0 0 1 0 1.06l-2.25 2.25a.75.75 0 1 1-1.06-1.06l.97-.97H1.75a.75.75 0 0 1 0-1.5h7.44l-.97-.97a.75.75 0 0 1 0-1.06" /></svg>);
const EnterIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path d="M19 19.5a1.5 1.5 0 0 1-1.5 1.5h-10A1.5 1.5 0 0 1 6 19.5V16a.75.75 0 0 1 1.5 0v3.5h10v-15h-10V8A.75.75 0 0 1 6 8V4.5A1.5 1.5 0 0 1 7.5 3h10A1.5 1.5 0 0 1 19 4.5z" /><path d="M11.72 8.47a.75.75 0 0 1 1.06 0l3 3a.75.75 0 0 1 0 1.06l-3 3a.75.75 0 1 1-1.06-1.06l1.72-1.72H3.75a.75.75 0 0 1 0-1.5h9.69l-1.72-1.72a.75.75 0 0 1 0-1.06" /></svg>);
const EnterIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path d="M26 26a2 2 0 0 1-2 2H10a2 2 0 0 1-2-2v-5a1 1 0 1 1 2 0v5h14V6H10v5a1 1 0 1 1-2 0V6a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" /><path d="M15.443 11.293a1 1 0 0 1 1.414 0l4 4a1 1 0 0 1 0 1.414l-4 4a1 1 0 0 1-1.414-1.414L17.736 17H5a1 1 0 1 1 0-2h12.736l-2.293-2.293a1 1 0 0 1 0-1.414" /></svg>);

export const EnterIcon = createIcon(EnterIcon16, EnterIcon24, EnterIcon32, "EnterIcon");