/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const EventIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M3.5 3.5v2.404h9.01V3.5zM3 2h10.01a1 1 0 0 1 1 1v3.404a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1m-.998 7.706c0-.69.56-1.25 1.25-1.25h9.997a.75.75 0 0 1 0 1.5H3.502v2.703h4.499a.75.75 0 0 1 0 1.5H3.252c-.69 0-1.25-.56-1.25-1.25zm13.139 2.432a.75.75 0 0 0-1.061-1.06l-2.472 2.471-.67-.67a.75.75 0 0 0-1.061 1.06l1.2 1.201a.75.75 0 0 0 1.061 0z" /></svg>);
const EventIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M18.5 5.5h-13V10h13zM5.5 4h13A1.5 1.5 0 0 1 20 5.5V10a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 4 10V5.5A1.5 1.5 0 0 1 5.5 4M4 14a1.5 1.5 0 0 1 1.5-1.5h13.75a.75.75 0 0 1 0 1.5H5.5v4.5h6.75a.75.75 0 0 1 0 1.5H5.5A1.5 1.5 0 0 1 4 18.5zm16.78 3.03a.75.75 0 1 0-1.06-1.06l-3.22 3.22-.97-.97a.75.75 0 1 0-1.06 1.06l1.5 1.5a.75.75 0 0 0 1.06 0z" /></svg>);
const EventIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M24 8H8v5h16zM8 6h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2M6 19a2 2 0 0 1 2-2h17a1 1 0 1 1 0 2H8v5h8a1 1 0 1 1 0 2H8a2 2 0 0 1-2-2zm21.707 3.707a1 1 0 0 0-1.414-1.414L22 25.586l-1.293-1.293a1 1 0 0 0-1.414 1.414l2 2a1 1 0 0 0 1.414 0z" /></svg>);

export const EventIcon = createIcon(EventIcon16, EventIcon24, EventIcon32, "EventIcon");