/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const EverythingReportIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path d="M11.438 2.046a.75.75 0 0 1 .274 1.025L9.299 7.25h4.826a.75.75 0 0 1 0 1.5H9.299l2.413 4.18a.75.75 0 0 1-1.299.75L8 9.5l-2.413 4.18a.75.75 0 1 1-1.299-.75l2.413-4.18H1.875a.75.75 0 0 1 0-1.5h4.826L4.288 3.07a.75.75 0 0 1 1.299-.75L8 6.5l2.413-4.18a.75.75 0 0 1 1.024-.274" /></svg>);
const EverythingReportIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path d="M16.313 4.53a.75.75 0 0 1 .274 1.025l-3.288 5.695h6.576a.75.75 0 0 1 0 1.5h-6.576l3.288 5.695a.75.75 0 0 1-1.299.75L12 13.5l-3.288 5.695a.75.75 0 0 1-1.299-.75l3.288-5.695H4.125a.75.75 0 0 1 0-1.5h6.576L7.413 5.555a.75.75 0 0 1 1.299-.75L12 10.5l3.288-5.695a.75.75 0 0 1 1.024-.274" /></svg>);
const EverythingReportIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path d="M21.75 6.04a1 1 0 0 1 .366 1.367L17.732 15H26.5a1 1 0 1 1 0 2h-8.768l4.384 7.593a1 1 0 1 1-1.732 1L16 18l-4.384 7.593a1 1 0 0 1-1.732-1L14.268 17H5.5a1 1 0 1 1 0-2h8.768L9.884 7.407a1 1 0 0 1 1.732-1L16 14l4.384-7.593a1 1 0 0 1 1.366-.366" /></svg>);

export const EverythingReportIcon = createIcon(EverythingReportIcon16, EverythingReportIcon24, EverythingReportIcon32, "EverythingReportIcon");