/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const ExitIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M2.495 1c-.69 0-1.25.56-1.25 1.25v11.497c0 .69.56 1.25 1.25 1.25h8.089c.69 0 1.25-.56 1.25-1.25v-.989a.75.75 0 0 0-1.5 0v.74h-7.59V2.5h7.595v.755a.75.75 0 0 0 1.5 0V2.25c0-.69-.56-1.25-1.25-1.25zm9.366 4.196a.75.75 0 0 0 0 1.061l.991.991H5.406a.75.75 0 0 0 0 1.5h7.446l-.991.992a.75.75 0 0 0 1.06 1.06l2.037-2.036a1.083 1.083 0 0 0 0-1.532L12.92 5.196a.75.75 0 0 0-1.06 0" /></svg>);
const ExitIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M6.498 3.008a1.5 1.5 0 0 0-1.5 1.5v14.995a1.5 1.5 0 0 0 1.5 1.5h9.991a1.5 1.5 0 0 0 1.5-1.5V17.26a.75.75 0 0 0-1.5 0v2.244h-9.99V4.508h9.997v2.256a.75.75 0 0 0 1.5 0V4.508a1.5 1.5 0 0 0-1.5-1.5zM17.892 8.47a.75.75 0 0 0 0 1.06l1.719 1.72H9a.75.75 0 0 0 0 1.5h10.61l-1.718 1.717a.75.75 0 0 0 1.061 1.06l2.763-2.762a1.083 1.083 0 0 0 0-1.532L18.953 8.47a.75.75 0 0 0-1.06 0" /></svg>);
const ExitIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M8 4a2 2 0 0 0-2 2v20a2 2 0 0 0 2 2h13.99a2 2 0 0 0 2-2v-2.994a1 1 0 0 0-2 0V26H8V6h14v3.009a1 1 0 1 0 2 0V6a2 2 0 0 0-2-2zm15.446 7.286a1 1 0 0 0 0 1.415l2.292 2.292H12a1 1 0 1 0 0 2h13.738l-2.292 2.292a1 1 0 0 0 1.414 1.414l3.764-3.764c.52-.52.52-1.364 0-1.885l-3.764-3.764a1 1 0 0 0-1.414 0" /></svg>);

export const ExitIcon = createIcon(ExitIcon16, ExitIcon24, ExitIcon32, "ExitIcon");