/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const FolderIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="m8.379 5.5-2-2H2.5v9h11v-7zM9 4h5a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h4.586a1 1 0 0 1 .707.293z" /></svg>);
const FolderIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="m12.28 8-2-2.5H4.5v12h15V8zM13 6.5h6.5A1.5 1.5 0 0 1 21 8v9.5a1.5 1.5 0 0 1-1.5 1.5h-15A1.5 1.5 0 0 1 3 17.5v-12A1.5 1.5 0 0 1 4.5 4h5.78a1.5 1.5 0 0 1 1.17.563z" /></svg>);
const FolderIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="m17.333 10-4-3H6v17h20V10zM18 8h8a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h7.333a2 2 0 0 1 1.2.4z" /></svg>);

export const FolderIcon = createIcon(FolderIcon16, FolderIcon24, FolderIcon32, "FolderIcon");