/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const GraduationHatIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M8.403 2.478a1 1 0 0 0-.796 0L1.95 4.941c-.802.349-.801 1.487.002 1.834l5.646 2.447a1 1 0 0 0 .796 0l2.106-.917v2.888h-5v-2.88L4 7.663v4.03a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V7.652l1.16-.505v1.41a.75.75 0 1 0 1.5 0V5.85a.8.8 0 0 0-.025-.192.98.98 0 0 0-.586-.734zM8.006 3.94 3.604 5.857l4.39 1.902 4.403-1.916z" /></svg>);
const GraduationHatIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M12.605 3.717a1.5 1.5 0 0 0-1.195 0L2.925 7.412c-1.203.524-1.201 2.23.002 2.752l8.47 3.67a1.5 1.5 0 0 0 1.194-.001L16.5 12.13v5.41h-9v-5.395l-1.5-.65v6.044a1.5 1.5 0 0 0 1.5 1.5h9a1.5 1.5 0 0 0 1.5-1.5v-6.062l2.478-1.078v2.185a.75.75 0 0 0 1.5 0V8.751l-.002-.061a1.48 1.48 0 0 0-.902-1.303zm7.873 5.046-8.47-3.67-8.484 3.694 8.469 3.67z" /></svg>);
const GraduationHatIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M16.944 5.394a2 2 0 0 0-1.594.002L4.037 10.32c-1.603.698-1.602 2.974.003 3.67l11.293 4.892a2 2 0 0 0 1.593-.001l5.211-2.269v7.212h-12v-7.193l-2-.867v8.06a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8.082l3.316-1.444v3.441a1 1 0 1 0 2 0v-5.6q0-.107-.02-.206a1.97 1.97 0 0 0-1.197-1.646zm10.497 6.728L16.149 7.23 4.836 12.154l11.292 4.893z" /></svg>);

export const GraduationHatIcon = createIcon(GraduationHatIcon16, GraduationHatIcon24, GraduationHatIcon32, "GraduationHatIcon");