/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const GripIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path d="M6.542 2.458a1.458 1.458 0 1 1-2.917 0 1.458 1.458 0 0 1 2.917 0m0 5.542a1.458 1.458 0 1 1-2.917 0 1.458 1.458 0 0 1 2.917 0m0 5.542a1.458 1.458 0 1 1-2.917 0 1.458 1.458 0 0 1 2.917 0m5.833-11.084a1.458 1.458 0 1 1-2.917 0 1.458 1.458 0 0 1 2.917 0m0 5.542a1.458 1.458 0 1 1-2.917 0 1.458 1.458 0 0 1 2.917 0m0 5.542a1.458 1.458 0 1 1-2.917 0 1.458 1.458 0 0 1 2.917 0" /></svg>);
const GripIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M10.5 5a2 2 0 1 1-4 0 2 2 0 0 1 4 0m0 7a2 2 0 1 1-4 0 2 2 0 0 1 4 0m-2 9a2 2 0 1 0 0-4 2 2 0 0 0 0 4m9-16a2 2 0 1 1-4 0 2 2 0 0 1 4 0m0 7a2 2 0 1 1-4 0 2 2 0 0 1 4 0m-2 9a2 2 0 1 0 0-4 2 2 0 0 0 0 4" /></svg>);
const GripIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path d="M13.75 6.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0m0 10a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0m0 9a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0m9.5-19a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0m0 10a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0m0 9a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0" /></svg>);

export const GripIcon = createIcon(GripIcon16, GripIcon24, GripIcon32, "GripIcon");