/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const HappinessIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M13.5 8a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0M15 8A7 7 0 1 1 1 8a7 7 0 0 1 14 0M5.25 6.5a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5m6.25-.75a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0M5.24 8.378a.75.75 0 0 0-1.48.244C4.1 10.673 5.86 12.25 8 12.25s3.9-1.577 4.24-3.628a.75.75 0 1 0-1.48-.244C10.536 9.732 9.378 10.75 8 10.75S5.464 9.732 5.24 8.378" /></svg>);
const HappinessIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M19.5 12a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0m1.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0M8 11a1 1 0 1 0 0-2 1 1 0 0 0 0 2m9-1a1 1 0 1 1-2 0 1 1 0 0 1 2 0m-9.51 2.628a.75.75 0 0 0-1.48.244C6.49 15.775 8.981 18 12 18c3.018 0 5.51-2.225 5.99-5.128a.75.75 0 1 0-1.48-.244C16.145 14.833 14.257 16.5 12 16.5s-4.145-1.667-4.51-3.872" /></svg>);
const HappinessIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M26 16c0 5.523-4.477 10-10 10S6 21.523 6 16 10.477 6 16 6s10 4.477 10 10m2 0c0 6.627-5.373 12-12 12S4 22.627 4 16 9.373 4 16 4s12 5.373 12 12m-16.75-1.5a1.25 1.25 0 1 0 0-2.5 1.25 1.25 0 0 0 0 2.5M22 13.25a1.25 1.25 0 1 1-2.5 0 1.25 1.25 0 0 1 2.5 0M9.987 16.837a1 1 0 0 0-1.974.326C8.653 21.033 11.975 24 16 24s7.346-2.967 7.987-6.837a1 1 0 0 0-1.974-.326C21.527 19.777 19.01 22 16 22s-5.527-2.222-6.013-5.163" /></svg>);

export const HappinessIcon = createIcon(HappinessIcon16, HappinessIcon24, HappinessIcon32, "HappinessIcon");