/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const HomeIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M3.5 6.321V12.5h1.8v-1.382a2.5 2.5 0 0 1 2.5-2.5h.4a2.5 2.5 0 0 1 2.5 2.5V12.5h1.8V6.321L8 2.721zm3.875-5.02a1 1 0 0 1 1.25 0l5 4a1 1 0 0 1 .375.78V13a1 1 0 0 1-1 1h-2.8a1 1 0 0 1-1-1v-1.882a1 1 0 0 0-1-1h-.4a1 1 0 0 0-1 1V13a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V6.081a1 1 0 0 1 .376-.78z" /></svg>);
const HomeIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M12 15a1.5 1.5 0 0 0-1.5 1.5v2A1.5 1.5 0 0 1 9 20H5.5A1.5 1.5 0 0 1 4 18.5v-7.82a1.5 1.5 0 0 1 .512-1.128l6.502-5.688a1.5 1.5 0 0 1 1.975 0l6.502 5.688a1.5 1.5 0 0 1 .512 1.129v7.818a1.5 1.5 0 0 1-1.5 1.5H15a1.5 1.5 0 0 1-1.5-1.5V16.5A1.5 1.5 0 0 0 12 15m0-1.5a3 3 0 0 1 3 3v2h3.503v-7.82l-6.501-5.687L5.5 10.681v7.818H9V16.5a3 3 0 0 1 3-3" /></svg>);
const HomeIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M16 20a2 2 0 0 0-2 2v2a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2V13.961a2 2 0 0 1 .75-1.562l8-6.4a2 2 0 0 1 2.5 0l8 6.4a2 2 0 0 1 .75 1.562V24a2 2 0 0 1-2 2h-4a2 2 0 0 1-2-2v-2a2 2 0 0 0-2-2m0-2a4 4 0 0 1 4 4v2h4V13.961l-8-6.4-8 6.4V24h4v-2a4 4 0 0 1 4-4" /></svg>);

export const HomeIcon = createIcon(HomeIcon16, HomeIcon24, HomeIcon32, "HomeIcon");