/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const ImageIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M2 3a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v10a1 1 0 0 1-.12.477A1 1 0 0 1 13 14H3a1 1 0 0 1-1-1zm1.5 5.012V3.5h9v4.793l-.773-.773a1 1 0 0 0-1.414 0L9.158 8.675 6.704 6.222a1 1 0 0 0-1.414 0zm7.361 4.488H3.5v-2.367l2.497-2.497zm1.639-.482v-1.604l-1.48-1.48-.802.802z" /></svg>);
const ImageIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M3 4.5A1.5 1.5 0 0 1 4.5 3h15A1.5 1.5 0 0 1 21 4.5v15a1.5 1.5 0 0 1-.181.715A1.5 1.5 0 0 1 19.5 21h-15A1.5 1.5 0 0 1 3 19.5zm1.5 0h15v8.689l-1.909-1.91a1.5 1.5 0 0 0-2.121 0l-1.733 1.734-3.68-3.68a1.5 1.5 0 0 0-2.122 0L4.5 12.768zm13.602 15H4.5v-4.61l4.496-4.497zm1.398-.724V15.31l-2.97-2.97-1.733 1.734z" /></svg>);
const ImageIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M26 6H6v20h20zM6 4a2 2 0 0 0-2 2v20a2 2 0 0 0 2 2h20a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2z" /><path fillRule="evenodd" d="m28 19.585-4.545-4.545a2 2 0 0 0-2.829 0l-2.31 2.31-4.907-4.906a2 2 0 0 0-2.829 0L4 19.024v2.828l7.994-7.994 14.138 14.138a2 2 0 0 0 1.663-1.114 2 2 0 0 0-.244-.296l-7.821-7.821 2.31-2.31L28 22.413z" /></svg>);

export const ImageIcon = createIcon(ImageIcon16, ImageIcon24, ImageIcon32, "ImageIcon");