/*** This file is generated by the generate-components script. Do not edit directly.*/
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";
const KebabIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" focusable="false" ref={ref} {...props}><path fill="currentColor" d="M9.458 2.458a1.458 1.458 0 1 1-2.916 0 1.458 1.458 0 0 1 2.916 0m0 5.542a1.458 1.458 0 1 1-2.916 0 1.458 1.458 0 0 1 2.916 0m0 5.542a1.458 1.458 0 1 1-2.916 0 1.458 1.458 0 0 1 2.916 0" /></svg>);
const KebabIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M14 5a2 2 0 1 1-4 0 2 2 0 0 1 4 0m0 7a2 2 0 1 1-4 0 2 2 0 0 1 4 0m-2 9a2 2 0 1 0 0-4 2 2 0 0 0 0 4" /></svg>);
const KebabIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M18.5 6.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0m0 10a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0M16 28a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5" /></svg>);

export const KebabIcon = createIcon(KebabIcon16, KebabIcon24, KebabIcon32, "KebabIcon");