/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const KeyIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path d="M9.75 5.5a.75.75 0 1 0 1.5 0 .75.75 0 0 0-1.5 0" /><path fillRule="evenodd" d="M6 6q0 .241.028.475l-3.735 3.732a1 1 0 0 0-.293.708V13a1 1 0 0 0 1 1h2.086a1 1 0 0 0 .707-.293l3.732-3.735Q9.76 10 10 10a4 4 0 1 0-4-4m-2.5 5.122 4.103-4.1-.086-.723a2.5 2.5 0 1 1 2.184 2.184l-.722-.086-4.1 4.103H3.5z" /></svg>);
const KeyIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path d="M15.5 9.5a1 1 0 1 0 0-2 1 1 0 0 0 0 2" /><path fillRule="evenodd" d="M14.5 15a5.5 5.5 0 1 0-5.336-4.164l-4.725 4.725A1.5 1.5 0 0 0 4 16.62v1.88A1.5 1.5 0 0 0 5.5 20h1.879a1.5 1.5 0 0 0 1.06-.44l4.725-4.723c.427.106.875.163 1.336.163m-9 1.621 5.325-5.324-.206-.824a4 4 0 1 1 2.908 2.908l-.824-.206L7.38 18.5H5.5z" /></svg>);
const KeyIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path d="M21.25 12a1.25 1.25 0 1 0 0-2.5 1.25 1.25 0 0 0 0 2.5" /><path fillRule="evenodd" d="M20 19a7 7 0 0 1-1.773-.227l-.727.727V22H15v2.5h-2.47V27H7a2 2 0 0 1-2-2v-2.794a2 2 0 0 1 .589-1.417l7.485-7.456.044-.043A7 7 0 1 1 20 19m-5.514-4.251.8-.749-.201-1.077a5 5 0 1 1 3.647 3.915l-1.11-.29-2.122 2.124V20H13v2.5h-2.47V25H7v-2.794z" /></svg>);

export const KeyIcon = createIcon(KeyIcon16, KeyIcon24, KeyIcon32, "KeyIcon");