/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const KeyResultIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M3.5 1.75a.75.75 0 1 0-1.5 0v12.5a.75.75 0 0 0 1.5 0v-3.745h9.075c1.181 0 1.703-1.488.78-2.227L11.45 6.755l1.905-1.524c.923-.739.401-2.226-.78-2.226H3.5zm0 7.255v-4.5h8.362L10.27 5.778a1.25 1.25 0 0 0 0 1.953l1.592 1.274z" /></svg>);
const KeyResultIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M6.5 3.75a.75.75 0 0 0-1.5 0v16.5a.75.75 0 0 0 1.5 0v-5.751h11.203c1.144 0 1.687-1.409.84-2.177L15.702 9.75l2.84-2.574C19.39 6.407 18.848 5 17.704 5H6.5zm.004 9.249v-6.5h10.551L14.49 8.822a1.25 1.25 0 0 0 0 1.853L17.055 13z" /></svg>);
const KeyResultIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M8 5a1 1 0 1 0-2 0v22a1 1 0 1 0 2 0v-8h16.662c1.388 0 2.031-1.722.984-2.632L21.193 12.5l4.453-3.868C26.693 7.722 26.05 6 24.662 6H8zm.005 12V8h15.319l-3.877 3.368a1.5 1.5 0 0 0 0 2.264L23.324 17z" /></svg>);

export const KeyResultIcon = createIcon(KeyResultIcon16, KeyResultIcon24, KeyResultIcon32, "KeyResultIcon");