/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const LearningPathStepIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M3 1a1 1 0 0 0-1 1v4a1 1 0 0 0 1 1h4.25v5.54l-1.72-1.72a.75.75 0 0 0-1.06 1.06l2.823 2.824a1 1 0 0 0 1.414 0l2.823-2.824a.75.75 0 1 0-1.06-1.06l-1.72 1.72V7H13a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zm.5 1.5v3h9v-3z" /></svg>);
const LearningPathStepIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M6.5 3A1.5 1.5 0 0 0 5 4.5v5A1.5 1.5 0 0 0 6.5 11h4.75v7.54l-2.22-2.22a.75.75 0 0 0-1.06 1.06l3.323 3.324a1 1 0 0 0 1.414 0l3.323-3.324a.75.75 0 1 0-1.06-1.06l-2.22 2.22V11h4.75A1.5 1.5 0 0 0 19 9.5v-5A1.5 1.5 0 0 0 17.5 3zm11 1.5h-11v5h11z" /></svg>);
const LearningPathStepIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M8 4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h7v11.796l-3.793-3.793a1 1 0 0 0-1.414 1.414l5.146 5.147a1.5 1.5 0 0 0 2.122 0l5.146-5.147a1 1 0 0 0-1.414-1.414L17 24.796V13h7a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2zm16 2H8v5h16z" /></svg>);

export const LearningPathStepIcon = createIcon(LearningPathStepIcon16, LearningPathStepIcon24, LearningPathStepIcon32, "LearningPathStepIcon");