/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const LearningPathIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M15 3a2 2 0 0 1-3.855.75H4.25a1.75 1.75 0 1 0 0 3.5h1.895a2 2 0 0 1 3.71 0h1.895a3.25 3.25 0 0 1 0 6.5H4.855a2 2 0 1 1 0-1.5h6.895a1.75 1.75 0 1 0 0-3.5H9.855a2 2 0 0 1-3.71 0H4.25a3.25 3.25 0 1 1 0-6.5h6.895A2 2 0 0 1 15 3m-1.5 0a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0M3 13.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1M8.5 8a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0" /></svg>);
const LearningPathIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M18.5 8a2.5 2.5 0 1 0-2.386-3.25H7a4 4 0 1 0 0 8h2.614a2.501 2.501 0 0 0 4.772 0H17a2.5 2.5 0 0 1 0 5H7.886a2.501 2.501 0 1 0 0 1.5H17a4 4 0 0 0 0-8h-2.614a2.501 2.501 0 0 0-4.772 0H7a2.5 2.5 0 0 1 0-5h9.115A2.5 2.5 0 0 0 18.5 8m0-1.5a1 1 0 1 0 0-2 1 1 0 0 0 0 2m-13 13a1 1 0 1 0 0-2 1 1 0 0 0 0 2M13 12a1 1 0 1 1-2 0 1 1 0 0 1 2 0" /></svg>);
const LearningPathIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M24.5 11a3.5 3.5 0 0 1-3.355-2.5H9.25a3.25 3.25 0 1 0 0 6.5h3.395a3.502 3.502 0 0 1 6.71 0h3.395a5.25 5.25 0 1 1 0 10.5H10.855A3.502 3.502 0 0 1 4 24.5a3.5 3.5 0 0 1 6.855-1H22.75a3.25 3.25 0 0 0 0-6.5h-3.395a3.502 3.502 0 0 1-6.71 0H9.25a5.25 5.25 0 1 1 0-10.5h11.895A3.502 3.502 0 0 1 28 7.5a3.5 3.5 0 0 1-3.5 3.5m0-2a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3M9 24.5a1.5 1.5 0 1 0-3 0 1.5 1.5 0 0 0 3 0m8.5-8.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0" /></svg>);

export const LearningPathIcon = createIcon(LearningPathIcon16, LearningPathIcon24, LearningPathIcon32, "LearningPathIcon");