/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const LocationIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M10.5 7a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0M9 7a1 1 0 1 1-2 0 1 1 0 0 1 2 0" /><path fillRule="evenodd" d="M14 6.833c0 3.832-4.044 6.998-5.492 8.009a.88.88 0 0 1-1.016 0C6.044 13.83 2 10.665 2 6.833 2 3.612 4.686 1 8 1s6 2.612 6 5.833m-1.5 0c0 1.395-.748 2.804-1.844 4.089-.91 1.065-1.95 1.916-2.656 2.438-.706-.521-1.746-1.373-2.656-2.438C4.248 9.637 3.5 8.228 3.5 6.833 3.5 4.48 5.475 2.5 8 2.5s4.5 1.98 4.5 4.333" /></svg>);
const LocationIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M15 10.5a3 3 0 1 1-6 0 3 3 0 0 1 6 0m-1.5 0a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0" /><path fillRule="evenodd" d="M19.5 10.455c0 4.835-4.798 8.867-6.719 10.288a1.3 1.3 0 0 1-1.562 0C9.299 19.323 4.5 15.29 4.5 10.455 4.5 6.338 8.134 3 12 3s7.5 3.338 7.5 7.455m-1.5 0c0 1.927-.965 3.815-2.308 5.484-1.275 1.585-2.771 2.825-3.692 3.515-.92-.69-2.417-1.93-3.692-3.515C6.965 14.27 6 12.382 6 10.455 6 7.21 8.918 4.5 12 4.5s6 2.71 6 5.955" /></svg>);
const LocationIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M20 14a4 4 0 1 1-8 0 4 4 0 0 1 8 0m-2 0a2 2 0 1 1-4 0 2 2 0 0 1 4 0" /><path fillRule="evenodd" d="M26 14c0 5.95-6.296 11.55-8.896 13.608a1.76 1.76 0 0 1-2.208 0C12.296 25.549 6 19.951 6 14 6 8.477 10.477 4 16 4s10 4.477 10 10m-2 0c0 2.303-1.243 4.75-3.041 7.023-1.7 2.15-3.706 3.904-4.959 4.907-1.254-1.003-3.258-2.758-4.959-4.907C9.244 18.749 8 16.303 8 14a8 8 0 1 1 16 0" /></svg>);

export const LocationIcon = createIcon(LocationIcon16, LocationIcon24, LocationIcon32, "LocationIcon");