/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const MaximizeIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M8.417 2.75a.75.75 0 0 1 .75-.75h4.083a.75.75 0 0 1 .75.75v4.083a.75.75 0 0 1-1.5 0V4.561L4.56 12.5h2.273a.75.75 0 0 1 0 1.5H2.75a.75.75 0 0 1-.75-.75V9.166a.75.75 0 0 1 1.5 0v2.273l7.94-7.94H9.167a.75.75 0 0 1-.75-.75" /></svg>);
const MaximizeIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M12.86 4.755a.75.75 0 0 1 .75-.75h5.635a.75.75 0 0 1 .75.75v5.635a.75.75 0 1 1-1.5 0V6.565l-11.93 11.93h3.825a.75.75 0 0 1 0 1.5H4.754a.75.75 0 0 1-.75-.75V13.61a.75.75 0 0 1 1.5 0v3.825l11.93-11.93H13.61a.75.75 0 0 1-.75-.75" /></svg>);
const MaximizeIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M17 7a1 1 0 0 1 1-1h7a1 1 0 0 1 1 1v7a1 1 0 1 1-2 0V9.416L9.415 24H14a1 1 0 1 1 0 2H7a1 1 0 0 1-1-1v-7a1 1 0 0 1 2 0v4.586L22.586 8.001H18a1 1 0 0 1-1-1" /></svg>);

export const MaximizeIcon = createIcon(MaximizeIcon16, MaximizeIcon24, MaximizeIcon32, "MaximizeIcon");