/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const MediaIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M1 3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1zm1.5 2.5v-2h1.75v2zm0 1.5v2h1.75V7zm0 3.5v2h1.75v-2zm3.25 2h4.5V8.75h-4.5zm6 0h1.75v-2h-1.75zM13.5 9V7h-1.75v2zm0-3.5v-2h-1.75v2zm-3.25-2h-4.5v3.75h4.5z" /></svg>);
const MediaIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M19.5 5A1.5 1.5 0 0 1 21 6.5v11a1.5 1.5 0 0 1-1.5 1.5h-15A1.5 1.5 0 0 1 3 17.5v-11A1.5 1.5 0 0 1 4.5 5zm-3 1.5h3V9h-3zM9 6.5h6v4.75H9zm-1.5 0h-3V9h3zm-3 4v3.25h3V10.5zm0 4.75v2.25h3v-2.25zM9 17.5h6v-4.75H9zm7.5 0h3v-2.25h-3zm3-3.75V10.5h-3v3.25z" /></svg>);
const MediaIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M4 8a2 2 0 0 1 2-2h20a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2zm17.821 0H26v2.5h-4.179zm-2 0h-7.643v7h7.643zm-9.643 0H6v2.5h4.179zM6 12.5V15h4.179v-2.5zM6 17v2.5h4.179V17zm0 4.5V24h4.179v-2.5zm6.179 2.5h7.642v-7h-7.643zm9.642 0H26v-2.5h-4.179zM26 19.5V17h-4.179v2.5zm0-4.5v-2.5h-4.179V15z" /></svg>);

export const MediaIcon = createIcon(MediaIcon16, MediaIcon24, MediaIcon32, "MediaIcon");