/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const MicrophoneIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M9.006 3.506v2.988a1.006 1.006 0 1 1-2.012 0V3.506a1.006 1.006 0 0 1 2.012 0m-3.512 0a2.506 2.506 0 0 1 5.012 0v2.988a2.506 2.506 0 0 1-5.012 0zm-.754 3.79a.75.75 0 0 0-1.48.241c.365 2.248 2 3.768 3.993 4.073v1.89h-.836a.75.75 0 0 0 0 1.5h3.166a.75.75 0 0 0 0-1.5h-.83v-1.889c1.99-.296 3.63-1.77 3.988-4.08a.75.75 0 0 0-1.482-.229C10.975 9.141 9.604 10.167 8 10.167c-1.586 0-2.968-1.075-3.26-2.87" /></svg>);
const MicrophoneIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M14 6.5v5a2 2 0 1 1-4 0v-5a2 2 0 1 1 4 0m-5.5 0a3.5 3.5 0 1 1 7 0v5a3.5 3.5 0 1 1-7 0zM7.25 12a.75.75 0 0 0-1.5 0c0 2.999 2.454 5.37 5.5 5.709V19.5h-2.5a.75.75 0 0 0 0 1.5h6.5a.75.75 0 1 0 0-1.5h-2.5v-1.79c3.039-.326 5.5-2.615 5.5-5.71a.75.75 0 0 0-1.5 0c0 2.368-2.048 4.25-4.75 4.25-2.692 0-4.75-1.969-4.75-4.25" /></svg>);
const MicrophoneIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M16 3a5 5 0 0 0-5 5v6a5 5 0 0 0 10 0V8a5 5 0 0 0-5-5m-3 5a3 3 0 1 1 6 0v6a3 3 0 1 1-6 0zm-4 6a1 1 0 1 0-2 0 9 9 0 0 0 8 8.945V26h-3a1 1 0 1 0 0 2h8a1 1 0 1 0 0-2h-3v-3.053c4.49-.48 8-4.16 8-8.947a1 1 0 1 0-2 0c0 4.007-3.121 7-7 7a7 7 0 0 1-7-7" /></svg>);

export const MicrophoneIcon = createIcon(MicrophoneIcon16, MicrophoneIcon24, MicrophoneIcon32, "MicrophoneIcon");