/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const MobileIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path d="M8 12.5A.75.75 0 1 0 8 11a.75.75 0 0 0 0 1.5" /><path fillRule="evenodd" d="M4 2a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1zm1.5 11.5v-11h5v11z" /></svg>);
const MobileIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path d="M12 18.5a1 1 0 1 0 0-2 1 1 0 0 0 0 2" /><path fillRule="evenodd" d="M6.5 4a1 1 0 0 1 1-1h9a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1h-9a1 1 0 0 1-1-1zM8 19.5v-15h8v15z" /></svg>);
const MobileIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path d="M16 24.5a1 1 0 1 0 0-2 1 1 0 0 0 0 2" /><path fillRule="evenodd" d="M9 5a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v22a1 1 0 0 1-1 1H10a1 1 0 0 1-1-1zm2 21V6h10v20z" /></svg>);

export const MobileIcon = createIcon(MobileIcon16, MobileIcon24, MobileIcon32, "MobileIcon");