/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const NewCommentIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M8 2.504a5.5 5.5 0 0 0 0 11h5.047l-.864-.865a.75.75 0 0 1-.035-1.023 5.52 5.52 0 0 0 1.221-4.812.75.75 0 0 1 1.464-.326 7.02 7.02 0 0 1-1.12 5.57l1.675 1.675a.75.75 0 0 1-.53 1.28H8A7 7 0 1 1 9.527 1.172.75.75 0 1 1 9.2 2.635 5.5 5.5 0 0 0 8 2.504" /><path fill="var(--hop-primary-icon)" d="M13.246 4.753a2 2 0 1 0 0-4 2 2 0 0 0 0 4" /></svg>);
const NewCommentIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M11.948 4.5a7.5 7.5 0 0 0 0 15h7.241l-1.55-1.551a.75.75 0 0 1-.036-1.023A7.47 7.47 0 0 0 19.448 12a7.5 7.5 0 0 0-.262-1.972.75.75 0 1 1 1.447-.393c.205.754.315 1.547.315 2.365 0 2.01-.66 3.866-1.773 5.364l2.355 2.356A.75.75 0 0 1 21 21h-9.052a9 9 0 1 1 2.461-17.659.75.75 0 1 1-.41 1.443 7.5 7.5 0 0 0-2.052-.284" /><path fill="var(--hop-primary-icon)" d="M19 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6" /></svg>);
const NewCommentIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M16 6C10.477 6 6 10.477 6 16s4.477 10 10 10h9.656l-2.068-2.068a1 1 0 0 1-.047-1.364A9.96 9.96 0 0 0 26 16c0-.998-.146-1.961-.417-2.869a1 1 0 0 1 1.916-.572A12 12 0 0 1 28 16c0 2.68-.88 5.155-2.363 7.152l3.14 3.14A1 1 0 0 1 28.07 28H16C9.373 28 4 22.627 4 16S9.373 4 16 4c1.133 0 2.23.157 3.272.452a1 1 0 1 1-.544 1.924A10 10 0 0 0 16 6" /><path fill="var(--hop-primary-icon)" d="M25 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8" /></svg>);

export const NewCommentIcon = createIcon(NewCommentIcon16, NewCommentIcon24, NewCommentIcon32, "NewCommentIcon");