/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const NewNoteIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fill="var(--hop-Icon-placeholder-primary-icon, #3B57FF)" d="M13.257 15.25a2 2 0 1 0 0-4 2 2 0 0 0 0 4" /><path fillRule="evenodd" d="M3.504 12.5V3.495h4.499V6.76c0 .69.56 1.25 1.25 1.25h3.254v1.738a.75.75 0 0 0 1.5 0V6.704c0-.331-.132-.65-.366-.884l-3.458-3.458a1.25 1.25 0 0 0-.884-.366H3.254c-.69 0-1.25.56-1.25 1.25v9.503c0 .69.56 1.25 1.25 1.25h6.502a.75.75 0 1 0 0-1.5zm8.705-5.99L9.503 3.803V6.51z" /></svg>);
const NewNoteIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M5.5 4A1.5 1.5 0 0 0 4 5.5v13A1.5 1.5 0 0 0 5.5 20h8.75a.75.75 0 0 0 0-1.5H5.5v-13h7.998v3.505a1.5 1.5 0 0 0 1.5 1.5H18.5v3.745a.75.75 0 0 0 1.5 0V9.41a1.5 1.5 0 0 0-.44-1.06l-3.91-3.91-.53.53.53-.53A1.5 1.5 0 0 0 14.59 4zm12.594 5.005-3.096-3.096v3.096z" /><path fill="var(--hop-Icon-placeholder-primary-icon, #3B57FF)" d="M19 22a3 3 0 1 0 0-6 3 3 0 0 0 0 6" /></svg>);
const NewNoteIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M8 6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h10.996a1 1 0 1 0 0-2H8V8h10v4a2 2 0 0 0 2 2h4v5a1 1 0 1 0 2 0v-6.186a2 2 0 0 0-.586-1.414l-.6.6.6-.6L20.6 6.586l-.6.6.6-.6A2 2 0 0 0 19.186 6zm12 2.814V12h3.186z" /><path fill="var(--hop-Icon-placeholder-primary-icon, #3B57FF)" d="M25 29a4 4 0 1 0 0-8 4 4 0 0 0 0 8" /></svg>);

export const NewNoteIcon = createIcon(NewNoteIcon16, NewNoteIcon24, NewNoteIcon32, "NewNoteIcon");