/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const NewTabIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M5.67 3.5H3.5v9h9v-2.164a.75.75 0 0 1 1.5 0v2.414c0 .69-.56 1.25-1.25 1.25h-9.5C2.56 14 2 13.44 2 12.75v-9.5C2 2.56 2.56 2 3.25 2h2.42a.75.75 0 1 1 0 1.5m.487 5.282a.75.75 0 0 0 1.06 1.061L12.5 4.561v2.127a.75.75 0 0 0 1.5 0V2.75a.75.75 0 0 0-.75-.75H9.313a.75.75 0 0 0 0 1.5h2.126z" /></svg>);
const NewTabIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M5.509 4.009a1.5 1.5 0 0 0-1.5 1.5V18.49a1.5 1.5 0 0 0 1.5 1.5H18.49a1.5 1.5 0 0 0 1.5-1.5v-3.743a.75.75 0 0 0-1.5 0v3.743H5.51V5.509h3.744a.75.75 0 1 0 0-1.5zm4.15 9.27a.75.75 0 1 0 1.061 1.062l7.771-7.772v3.62a.75.75 0 0 0 1.5 0V4.76a.75.75 0 0 0-.75-.75h-5.43a.75.75 0 0 0 0 1.5h3.62l-7.772 7.77Z" /></svg>);
const NewTabIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M13.002 8H8v16h16v-5.003a1 1 0 0 1 2 0v5.253A1.75 1.75 0 0 1 24.25 26H7.75A1.75 1.75 0 0 1 6 24.25V7.75C6 6.784 6.784 6 7.75 6h5.252a1 1 0 0 1 0 2m.04 9.543a1 1 0 0 0 1.415 1.414L24 9.414v4.336a1 1 0 1 0 2 0V7a1 1 0 0 0-1-1h-6.75a1 1 0 1 0 0 2h4.336l-9.543 9.543" /></svg>);

export const NewTabIcon = createIcon(NewTabIcon16, NewTabIcon24, NewTabIcon32, "NewTabIcon");