/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const NotebookIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M3.5 4.999V7.25h.75a.75.75 0 0 1 0 1.5H3.5v2.258h.75a.75.75 0 1 1 0 1.5H3.5v.992h8.986v-11H3.5v.999h.75a.75.75 0 1 1 0 1.5H3.5M2 12.509V14a1 1 0 0 0 1 1h9.986a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1.499h-.25a.75.75 0 1 0 0 1.5H2V7.25h-.25a.75.75 0 0 0 0 1.5H2v2.258h-.25a.75.75 0 1 0 0 1.5H2m3.5-6.747a.75.75 0 0 1 .75-.75h3.5a.75.75 0 0 1 0 1.5h-3.5a.75.75 0 0 1-.75-.75" /></svg>);
const NotebookIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M17.5 4.5h-11v2h.25a.75.75 0 0 1 0 1.5H6.5v3.25h.25a.75.75 0 0 1 0 1.5H6.5V16h.25a.75.75 0 0 1 0 1.5H6.5v2h11zM5 17.5v2A1.5 1.5 0 0 0 6.5 21h11a1.5 1.5 0 0 0 1.5-1.5v-15A1.5 1.5 0 0 0 17.5 3h-11A1.5 1.5 0 0 0 5 4.5v2h-.25a.75.75 0 0 0 0 1.5H5v3.25h-.25a.75.75 0 0 0 0 1.5H5V16h-.25a.75.75 0 0 0 0 1.5zm4-8.75A.75.75 0 0 1 9.75 8h4.5a.75.75 0 0 1 0 1.5h-4.5A.75.75 0 0 1 9 8.75" /></svg>);
const NotebookIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M24 6H8v3h1a1 1 0 0 1 0 2H8v4h1a1 1 0 1 1 0 2H8v4h1a1 1 0 1 1 0 2H8v3h16zM6 23v3a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2H8a2 2 0 0 0-2 2v3H5a1 1 0 0 0 0 2h1v4H5a1 1 0 1 0 0 2h1v4H5a1 1 0 1 0 0 2zm7-12a1 1 0 1 0 0 2h6a1 1 0 1 0 0-2z" /></svg>);

export const NotebookIcon = createIcon(NotebookIcon16, NotebookIcon24, NotebookIcon32, "NotebookIcon");