/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const OpenSmileIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M13.5 8a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0M15 8A7 7 0 1 1 1 8a7 7 0 0 1 14 0M5 8.48a.75.75 0 0 0-.738.881c.308 1.743 1.89 3.02 3.738 3.02s3.43-1.277 3.739-3.02a.75.75 0 0 0-.739-.88H5Zm3 2.4c-.786 0-1.46-.363-1.87-.9h3.74c-.41.537-1.084.9-1.87.9M5.958 6.261a.875.875 0 1 1-1.75 0 .875.875 0 0 1 1.75 0m4.959.875a.875.875 0 1 0 0-1.75.875.875 0 0 0 0 1.75" /></svg>);
const OpenSmileIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M19.5 12a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0m1.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0M8 11a1 1 0 1 0 0-2 1 1 0 0 0 0 2m9-1a1 1 0 1 1-2 0 1 1 0 0 1 2 0M6.75 12a.75.75 0 0 0-.74.872C6.49 15.775 8.981 18 12 18c3.018 0 5.51-2.225 5.99-5.128a.75.75 0 0 0-.74-.872zM12 16.5c-1.948 0-3.622-1.242-4.278-3h8.556c-.656 1.758-2.33 3-4.278 3" /></svg>);
const OpenSmileIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M26 16c0 5.523-4.477 10-10 10S6 21.523 6 16 10.477 6 16 6s10 4.477 10 10m2 0c0 6.627-5.373 12-12 12S4 22.627 4 16 9.373 4 16 4s12 5.373 12 12m-16.75-1.5a1.25 1.25 0 1 0 0-2.5 1.25 1.25 0 0 0 0 2.5M22 13.25a1.25 1.25 0 1 1-2.5 0 1.25 1.25 0 0 1 2.5 0M9 16a1 1 0 0 0-.987 1.163C8.653 21.033 11.975 24 16 24s7.347-2.967 7.987-6.837A1 1 0 0 0 23 16zm7 6c-2.598 0-4.829-1.656-5.703-4h11.406c-.874 2.344-3.105 4-5.703 4" /></svg>);

export const OpenSmileIcon = createIcon(OpenSmileIcon16, OpenSmileIcon24, OpenSmileIcon32, "OpenSmileIcon");