/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const OpenRoleIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="m3.362 6.299 1.822-4.247a1.75 1.75 0 0 1 2.796-.594l3.392 3.138.886-.188a1 1 0 0 1 1.186.77l1.08 5.087a1 1 0 0 1-.77 1.186l-9.78 2.079a1 1 0 0 1-1.187-.77L1.706 7.673a1 1 0 0 1 .77-1.186zm3.2-3.655a.25.25 0 0 1 .4-.085l2.614 2.42-4.418.938zM4.15 11.959 3.277 7.85l8.803-1.87.874 4.108z" /></svg>);
const OpenRoleIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="m6.302 9.826 2.364-5.512a1.75 1.75 0 0 1 2.797-.595l4.402 4.074 1.577-.335a1 1 0 0 1 1.186.77l1.455 6.847a1 1 0 0 1-.77 1.186L6.597 18.964a1 1 0 0 1-1.186-.77l-1.456-6.847a1 1 0 0 1 .77-1.186zm3.743-4.921a.25.25 0 0 1 .4-.085l3.624 3.355-5.971 1.27zM6.774 17.393l-1.247-5.869L17.264 9.03l1.248 5.87z" /></svg>);
const OpenRoleIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M15.604 4.638a2 2 0 0 0-3.196.68L9.069 13.1l-2.428.516a1 1 0 0 0-.77 1.186l2.08 9.782a1 1 0 0 0 1.185.77l17.607-3.742a1 1 0 0 0 .77-1.186l-2.079-9.782a1 1 0 0 0-1.186-.77l-2.428.516zm3.822 6.262-5.18-4.794-2.782 6.486zM9.699 23.19l-1.664-7.824 15.65-3.327 1.664 7.825z" /></svg>);

export const OpenRoleIcon = createIcon(OpenRoleIcon16, OpenRoleIcon24, OpenRoleIcon32, "OpenRoleIcon");