/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const PeaceIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M8 1a7.001 7.001 0 0 0-4.951 11.948l.001.002.002.001A6.968 6.968 0 0 0 8 15a6.968 6.968 0 0 0 4.948-2.048l.002-.002.002-.002A6.971 6.971 0 0 0 15 8a7.001 7.001 0 0 0-7-7m-.75 1.55a5.501 5.501 0 0 0-3.633 8.773L7.25 7.689V2.551Zm0 7.26-2.573 2.573A5.464 5.464 0 0 0 7.25 13.45V9.811m1.5 3.64a5.464 5.464 0 0 0 2.573-1.067L8.75 9.811v3.638m0-5.76V2.55a5.501 5.501 0 0 1 3.633 8.773z" /></svg>);
const PeaceIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M12 3a9 9 0 1 0 .002 18A9 9 0 0 0 12 3m-.75 1.537a7.5 7.5 0 0 0-5.057 12.21l5.057-5.058zm0 9.274-3.997 3.996a7.458 7.458 0 0 0 3.997 1.656v-5.652m1.5 5.652a7.458 7.458 0 0 0 3.997-1.656l-3.997-3.996zm0-7.774V4.537a7.5 7.5 0 0 1 5.057 12.21l-5.057-5.058" /></svg>);
const PeaceIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M16 4c-.337 0-.67.014-1 .041C8.84 4.55 4 9.71 4 16a11.952 11.952 0 0 0 3.515 8.485A11.947 11.947 0 0 0 16 28a11.947 11.947 0 0 0 8.485-3.515A11.952 11.952 0 0 0 28 16c0-6.29-4.84-11.45-11-11.959A12.16 12.16 0 0 0 16 4m-1 2.05c-5.053.5-9 4.764-9 9.95 0 2.402.845 4.604 2.257 6.329L15 15.586V6.049Zm0 12.364-5.329 5.329A9.945 9.945 0 0 0 15 25.951zm2 7.537a9.945 9.945 0 0 0 5.329-2.208L17 18.414zm0-10.365V6.049c5.053.502 9 4.766 9 9.951a9.951 9.951 0 0 1-2.257 6.329z" /></svg>);

export const PeaceIcon = createIcon(PeaceIcon16, PeaceIcon24, PeaceIcon32, "PeaceIcon");