/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const PlaySolidIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="m5.5 14.062 9-5.196a1 1 0 0 0 0-1.732l-9-5.196a1 1 0 0 0-1.5.866v10.392a1 1 0 0 0 1.5.866" /></svg>);
const PlaySolidIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M21.25 13.299c1-.577 1-2.02 0-2.598L8.5 3.34a1.5 1.5 0 0 0-2.25 1.299V19.36a1.5 1.5 0 0 0 2.25 1.3z" /></svg>);
const PlaySolidIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M11.5 27.258 28 17.732c1.333-.77 1.333-2.694 0-3.464L11.5 4.742c-1.333-.77-3 .192-3 1.732v19.052c0 1.54 1.667 2.502 3 1.732" /></svg>);

export const PlaySolidIcon = createIcon(PlaySolidIcon16, PlaySolidIcon24, PlaySolidIcon32, "PlaySolidIcon");