/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const QuestionIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M8 13.5a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14m.75-3.75a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0M7.111 6.156a.889.889 0 1 1 1.156.848c-.441.139-1.017.565-1.017 1.29v.866a.75.75 0 1 0 1.5 0v-.736a2.39 2.39 0 1 0-3.139-2.268.75.75 0 1 0 1.5 0" /></svg>);
const QuestionIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M12 19.5a7.5 7.5 0 1 0 0-15 7.5 7.5 0 0 0 0 15m0 1.5a9 9 0 1 0 0-18 9 9 0 0 0 0 18m.956-4.204a.956.956 0 1 1-1.912 0 .956.956 0 0 1 1.912 0m-2.651-7.35a1.695 1.695 0 1 1 2.04 1.66c-.526.108-1.095.565-1.095 1.285v1.537a.75.75 0 0 0 1.5 0v-1.376a3.196 3.196 0 1 0-3.945-3.107.75.75 0 0 0 1.5 0" /></svg>);
const QuestionIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M16 26c5.523 0 10-4.477 10-10S21.523 6 16 6 6 10.477 6 16s4.477 10 10 10m0 2c6.627 0 12-5.373 12-12S22.627 4 16 4 4 9.373 4 16s5.373 12 12 12m1.25-6.25a1.25 1.25 0 1 1-2.5 0 1.25 1.25 0 0 1 2.5 0m-3.427-8.573a2.176 2.176 0 1 1 2.52 2.15c-.662.104-1.343.665-1.343 1.526V18.5a1 1 0 1 0 2 0v-1.268a4.178 4.178 0 1 0-5.177-4.055 1 1 0 0 0 2 0" /></svg>);

export const QuestionIcon = createIcon(QuestionIcon16, QuestionIcon24, QuestionIcon32, "QuestionIcon");