/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const QuizLessonIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path d="M10.53 7.53a.75.75 0 1 0-1.06-1.06L7.5 8.44l-.97-.97a.75.75 0 0 0-1.06 1.06l1.5 1.5a.75.75 0 0 0 1.06 0z" /><path fillRule="evenodd" d="M2 3a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1zm1.5 9.5v-9h9v9z" /></svg>);
const QuizLessonIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path d="M16.553 9.507a.75.75 0 0 0-1.106-1.014l-4.794 5.23a.25.25 0 0 1-.361.008L8.53 11.97a.75.75 0 0 0-1.06 1.06l1.761 1.762a1.75 1.75 0 0 0 2.528-.055z" /><path fillRule="evenodd" d="M4 5.5A1.5 1.5 0 0 1 5.5 4h13A1.5 1.5 0 0 1 20 5.5v13a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 4 18.5zm1.5 0h13v13h-13z" /></svg>);
const QuizLessonIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path d="M22.207 13.207a1 1 0 0 0-1.414-1.414l-7.236 7.236-2.298-2.68a1 1 0 0 0-1.518 1.302l2.297 2.68a2 2 0 0 0 2.933.113z" /><path fillRule="evenodd" d="M6 8a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2zm2 0h16v16H8z" /></svg>);

export const QuizLessonIcon = createIcon(QuizLessonIcon16, QuizLessonIcon24, QuizLessonIcon32, "QuizLessonIcon");