/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const ReminderIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M2.93 8a5.285 5.285 0 1 1 5.285 5.285.75.75 0 0 0 0 1.5A6.785 6.785 0 1 0 1.429 8v.086l-.153-.123A.75.75 0 0 0 .34 9.134l1.372 1.098a.75.75 0 0 0 .937 0L4.02 9.134a.75.75 0 0 0-.938-1.171l-.153.123V8m5.842-2.84a.75.75 0 0 0-1.5 0V7.5c0 .69.56 1.25 1.25 1.25h2.34a.75.75 0 0 0 0-1.5h-2.09V5.16" /></svg>);
const ReminderIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="m5.22 10.767-.701.7A7.5 7.5 0 1 1 12 19.5a.75.75 0 0 0 0 1.5 9 9 0 1 0-8.986-9.5l-.734-.733a.75.75 0 0 0-1.06 1.06l2 2a.75.75 0 0 0 1.06 0l2-2a.75.75 0 0 0-1.06-1.06m7.53-4.017a.75.75 0 0 0-1.5 0v4.5a1.5 1.5 0 0 0 1.5 1.5h4.5a.75.75 0 0 0 0-1.5h-4.5z" /></svg>);
const ReminderIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="m7.293 14.293-1.284 1.284C6.23 10.25 10.619 6 16 6c5.523 0 10 4.477 10 10s-4.477 10-10 10a1 1 0 0 0 0 2c6.628 0 12-5.373 12-12S22.628 4 16 4C9.509 4 4.222 9.154 4.007 15.593l-1.3-1.3a1 1 0 0 0-1.414 1.414l3 3a1 1 0 0 0 1.414 0l3-3a1 1 0 1 0-1.414-1.414M17 9a1 1 0 1 0-2 0v6a2 2 0 0 0 2 2h6a1 1 0 1 0 0-2h-6z" /></svg>);

export const ReminderIcon = createIcon(ReminderIcon16, ReminderIcon24, ReminderIcon32, "ReminderIcon");