/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const ReplyIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M7.987 3.506H2.505v6.636h9.994l-1.104-1.028a.75.75 0 1 1 1.023-1.098l2.236 2.083c.46.428.46 1.157 0 1.586l-2.236 2.082a.75.75 0 1 1-1.022-1.097l1.103-1.028H2.255c-.69 0-1.25-.56-1.25-1.25V3.256c0-.69.56-1.25 1.25-1.25h5.732a.75.75 0 0 1 0 1.5" /></svg>);
const ReplyIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M4.344 5a1.5 1.5 0 0 0-1.5 1.5v8a1.5 1.5 0 0 0 1.5 1.5h13.964l-1.867 1.695a.75.75 0 1 0 1.008 1.11l3.033-2.753a1.083 1.083 0 0 0 0-1.604l-3.033-2.754a.75.75 0 1 0-1.008 1.111l1.867 1.695H4.344v-8h7.517a.75.75 0 0 0 0-1.5H4.344" /></svg>);
const ReplyIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" focusable="false" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M5.833 6a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h18.605l-2.489 2.26a1 1 0 1 0 1.344 1.48l4.134-3.752a1.333 1.333 0 0 0 0-1.975l-4.134-3.753a1 1 0 1 0-1.344 1.48L24.44 20H5.832V8H15.85a1 1 0 1 0 0-2z" /></svg>);

export const ReplyIcon = createIcon(ReplyIcon16, ReplyIcon24, ReplyIcon32, "ReplyIcon");