/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const ReportIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M3.5 3.5H8v3.26c0 .69.56 1.25 1.25 1.25h3.25v4.49h-9zm6 3.01V3.906l2.604 2.604H9.499M2 3v10a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V6.7a1 1 0 0 0-.293-.707l-3.7-3.7A1 1 0 0 0 9.3 2H3a1 1 0 0 0-1 1m9.264 6.807a.75.75 0 0 0-.939-1.17l-1.731 1.39-1.102-.755a.75.75 0 0 0-.902.04l-1.62 1.337a.75.75 0 1 0 .955 1.157l1.185-.978 1.095.75a.75.75 0 0 0 .894-.033z" /></svg>);
const ReportIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M5.5 18.5h13v-8.497h-2.994a1.5 1.5 0 0 1-1.5-1.5V5.5H5.5zM15.506 5.628l2.875 2.875h-2.875zM18.5 20h-13A1.5 1.5 0 0 1 4 18.5v-13A1.5 1.5 0 0 1 5.5 4h9.878a1.5 1.5 0 0 1 1.061.44l3.122 3.12A1.5 1.5 0 0 1 20 8.622V18.5a1.5 1.5 0 0 1-1.5 1.5m-1.718-7.217a.75.75 0 0 0-1.064-1.057l-2.95 2.972-1.954-1.679a.75.75 0 0 0-1.028.048L7.21 15.734a.75.75 0 1 0 1.08 1.042l2.083-2.158 1.946 1.672a.75.75 0 0 0 1.02-.04z" /></svg>);
const ReportIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M8 24h16V14h-4a2 2 0 0 1-2-2V8H8zM20 8.828 23.172 12H20zM24 26H8a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h11.172a2 2 0 0 1 1.414.586l4.828 4.828A2 2 0 0 1 26 12.828V24a2 2 0 0 1-2 2m-1.977-8.295a1 1 0 0 0-1.42-1.41l-3.647 3.673-2.397-2.06a1 1 0 0 0-1.371.064l-3.22 3.333a1 1 0 1 0 1.439 1.39l2.564-2.655 2.387 2.052a1 1 0 0 0 1.361-.054l4.304-4.333" /></svg>);

export const ReportIcon = createIcon(ReportIcon16, ReportIcon24, ReportIcon32, "ReportIcon");