/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const ScreenShareIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path d="M8.884 4.928a1.25 1.25 0 0 0-1.768 0L4.988 7.056a.75.75 0 0 0 1.06 1.06L8 6.167l1.951 1.95a.75.75 0 0 0 1.061-1.06z" /><path fillRule="evenodd" d="M1 3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1zm1.5 9.5v-9h11v9z" /><path fillRule="evenodd" d="M8.75 10.874V5.582a.75.75 0 1 0-1.5 0v5.292a.75.75 0 0 0 1.5 0" /></svg>);
const ScreenShareIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M4 6.643a1.5 1.5 0 0 1 1.5-1.5h13a1.5 1.5 0 0 1 1.5 1.5v10.714a1.5 1.5 0 0 1-1.5 1.5h-13a1.5 1.5 0 0 1-1.5-1.5zm1.5 0h13v10.714h-13z" /><path d="M12.874 8.738a1.25 1.25 0 0 0-1.768 0l-2.482 2.483a.75.75 0 0 0 1.06 1.06l2.306-2.306 2.306 2.306a.75.75 0 0 0 1.06-1.06z" /><path fillRule="evenodd" d="M11.24 14.874V9.126a.75.75 0 0 1 1.5 0v5.748a.75.75 0 0 1-1.5 0" /></svg>);
const ScreenShareIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path d="M15.116 11.967a1.25 1.25 0 0 1 1.768 0l3.192 3.191a.75.75 0 0 1-1.061 1.061l-2.265-2.265v5.724a.75.75 0 1 1-1.5 0v-5.723l-2.265 2.264a.75.75 0 1 1-1.06-1.06z" /><path fillRule="evenodd" d="M6 9.429a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2V22.57a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2zm2 0h16V22.57H8z" /></svg>);

export const ScreenShareIcon = createIcon(ScreenShareIcon16, ScreenShareIcon24, ScreenShareIcon32, "ScreenShareIcon");