/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const SendIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M7.255 14.333c.483.965 1.878.907 2.279-.095l4.532-11.331a.75.75 0 0 0-.975-.975L1.761 6.466c-1 .4-1.059 1.796-.094 2.279l3.725 1.862zM5.803 9.135 2.836 7.652l7.42-2.97zm5.514-3.392-4.453 4.453 1.484 2.968z" /></svg>);
const SendIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M11.393 20.34c.482.964 1.878.906 2.279-.095l5.962-14.906a.75.75 0 0 0-.975-.975L3.755 10.328c-1.001.4-1.06 1.797-.094 2.279l5.154 2.576zm-2.167-6.63-4.397-2.197 10.994-4.4zm7.658-5.537-6.597 6.598 2.199 4.399z" /></svg>);
const SendIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M15.261 27.192c.579 1.158 2.254 1.088 2.734-.114l7.851-19.627a1 1 0 0 0-1.3-1.3L4.922 14.004c-1.201.481-1.27 2.156-.113 2.735l6.968 3.483zm-2.937-8.933-5.626-2.811 14.067-5.63zm9.856-7.027-8.442 8.442 2.814 5.628z" /></svg>);

export const SendIcon = createIcon(SendIcon16, SendIcon24, SendIcon32, "SendIcon");