/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const ShareIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M9.747 4.015a2.13 2.13 0 1 1 .797 1.661l-3.8 2.194 3.997 2.313a2.13 2.13 0 1 1-.91 1.207l-3.96-2.292a2.13 2.13 0 1 1-.012-2.45l3.92-2.262a2 2 0 0 1-.032-.371m2.13-.63a.63.63 0 1 0 0 1.26.63.63 0 0 0 0-1.26M3.494 7.883a.63.63 0 1 1 1.26 0 .63.63 0 0 1-1.26 0m7.753 4.103a.63.63 0 1 1 1.259 0 .63.63 0 0 1-1.259 0" /></svg>);
const ShareIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M15.086 6.453a2.457 2.457 0 1 1 .9 1.901l-6.32 3.647 6.311 3.652a2.457 2.457 0 1 1-.81 1.264l-6.535-3.782a2.457 2.457 0 1 1 .01-2.274l6.528-3.768a2.5 2.5 0 0 1-.084-.64m2.457-.957a.957.957 0 1 0 0 1.914.957.957 0 0 0 0-1.914M5.5 11.988a.957.957 0 1 1 1.914 0 .957.957 0 0 1-1.914 0m11.085 5.559a.957.957 0 1 1 1.914 0 .957.957 0 0 1-1.914 0" /></svg>);
const ShareIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M19.761 9.114a3.12 3.12 0 1 1 1.18 2.443l-7.7 4.445 7.689 4.45a3.12 3.12 0 1 1-1.078 1.687l-8.008-4.635A3.119 3.119 0 0 1 6 15.984a3.12 3.12 0 0 1 5.858-1.494l7.997-4.615a3 3 0 0 1-.094-.761m3.12-1.12a1.12 1.12 0 1 0 0 2.24 1.12 1.12 0 0 0 0-2.24M8 15.984a1.12 1.12 0 1 1 2.239 0 1.12 1.12 0 0 1-2.239 0m13.761 6.902a1.12 1.12 0 1 1 2.24 0 1.12 1.12 0 0 1-2.24 0" /></svg>);

export const ShareIcon = createIcon(ShareIcon16, ShareIcon24, ShareIcon32, "ShareIcon");