/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const ShieldIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M7.682 1.077a.75.75 0 0 1 .636 0l5.248 2.453a.75.75 0 0 1 .433.679v3.237c0 3.482-2.463 6.728-5.826 7.528a.75.75 0 0 1-.346 0C4.464 14.174 2 10.928 2 7.446V4.21a.75.75 0 0 1 .433-.68l5.248-2.452m-4.18 3.61v2.01H7.25V2.933L3.501 4.686ZM8.75 2.933v3.762h3.749v-2.01L8.75 2.934m3.701 5.262H8.75v5.01c1.964-.855 3.425-2.82 3.701-5.01m-5.201 5.01c-1.964-.855-3.425-2.82-3.701-5.01H7.25z" /></svg>);
const ShieldIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M11.65 3.084a.75.75 0 0 1 .692 0l6.242 3.241a.75.75 0 0 1 .404.666v4.278c0 4.437-2.833 8.658-6.8 9.706a.748.748 0 0 1-.383 0c-3.968-1.048-6.801-5.27-6.801-9.706V6.99a.75.75 0 0 1 .404-.666l6.242-3.24M6.504 7.447v3.072h4.742V4.984zm6.242-2.463v5.535h4.742V7.447l-4.742-2.463m4.711 7.035h-4.71v7.172c2.529-1.135 4.447-3.975 4.71-7.172m-6.21 7.172c-2.53-1.135-4.449-3.975-4.712-7.172h4.711v7.172" /></svg>);
const ShieldIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M15.567 4.099a1 1 0 0 1 .866 0l9 4.321a1 1 0 0 1 .567.901v5.704c0 5.972-4.118 11.568-9.763 12.946a1.001 1.001 0 0 1-.474 0C10.118 26.594 6 20.998 6 15.026V9.32a1 1 0 0 1 .567-.901l9-4.321M8 9.95v4.074h7V6.589L8 9.951m9-3.362v7.436h7V9.95l-7-3.362m6.955 9.436H17v9.609c3.761-1.49 6.57-5.334 6.955-9.61M15 25.634c-3.761-1.49-6.57-5.334-6.955-9.61H15z" /></svg>);

export const ShieldIcon = createIcon(ShieldIcon16, ShieldIcon24, ShieldIcon32, "ShieldIcon");