/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const SliderIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M8 12.5a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9M8 14a6 6 0 0 0 5.917-5H15a1 1 0 1 0 0-2h-1.083A6.002 6.002 0 0 0 2.083 7H1a1 1 0 0 0 0 2h1.083A6 6 0 0 0 8 14m.75-8.25a.75.75 0 0 0-1.5 0v4.5a.75.75 0 0 0 1.5 0zm-3 .75a.75.75 0 0 1 .75.75v1.5a.75.75 0 0 1-1.5 0v-1.5a.75.75 0 0 1 .75-.75m5.25.75a.75.75 0 0 0-1.5 0v1.5a.75.75 0 0 0 1.5 0z" /></svg>);
const SliderIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M12 17.5a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11m0 1.5a7 7 0 0 0 6.71-5H20a2 2 0 1 0 0-4h-1.29a7.003 7.003 0 0 0-13.42 0H4a2 2 0 1 0 0 4h1.29c.86 2.892 3.539 5 6.71 5m8-6.5h-1.018a7 7 0 0 0 0-1H20a.5.5 0 0 1 0 1m-16-1h1.018a7 7 0 0 0 0 1H4a.5.5 0 0 1 0-1m8.75-1.75a.75.75 0 0 0-1.5 0v4.5a.75.75 0 0 0 1.5 0zm-3.5.25a.75.75 0 0 1 .75.75v2.5a.75.75 0 0 1-1.5 0v-2.5a.75.75 0 0 1 .75-.75m6.25.75a.75.75 0 0 0-1.5 0v2.5a.75.75 0 0 0 1.5 0z" /></svg>);
const SliderIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M16 24a8 8 0 1 0 0-16 8 8 0 0 0 0 16m0 2c4.478 0 8.268-2.943 9.542-7H27a3 3 0 1 0 0-6h-1.458C24.269 8.944 20.479 6 16 6s-8.268 2.943-9.542 7H5a3 3 0 1 0 0 6h1.458c1.274 4.057 5.064 7 9.542 7m11-9h-1.05a10 10 0 0 0 0-2H27a1 1 0 1 1 0 2M5 15h1.05a10 10 0 0 0 0 2H5a1 1 0 1 1 0-2m12-2a1 1 0 1 0-2 0v6a1 1 0 1 0 2 0zm-5 0a1 1 0 0 1 1 1v4a1 1 0 1 1-2 0v-4a1 1 0 0 1 1-1m9 1a1 1 0 1 0-2 0v4a1 1 0 1 0 2 0z" /></svg>);

export const SliderIcon = createIcon(SliderIcon16, SliderIcon24, SliderIcon32, "SliderIcon");