/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const StartOverIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} fill="none" viewBox="0 0 16 16" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M4.764 6.861a.75.75 0 0 1-1.022 1.098L1.505 5.876a1.083 1.083 0 0 1 0-1.586l2.237-2.083a.75.75 0 1 1 1.022 1.098L3.66 4.333h10.245c.69 0 1.25.56 1.25 1.25v7.136c0 .69-.56 1.25-1.25 1.25H8.172a.75.75 0 0 1 0-1.5h5.483V5.833H3.66L4.764 6.86" /></svg>);
const StartOverIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} fill="none" viewBox="0 0 24 24" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M7.403 11.195a.75.75 0 1 1-1.009 1.11L3.362 9.552a1.083 1.083 0 0 1 0-1.604l3.032-2.753a.75.75 0 1 1 1.009 1.11L5.536 8H19.5A1.5 1.5 0 0 1 21 9.5v8a1.5 1.5 0 0 1-1.5 1.5h-7.517a.75.75 0 0 1 0-1.5H19.5v-8H5.536z" /></svg>);
const StartOverIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} fill="none" viewBox="0 0 32 32" ref={ref} {...props}><path fill="currentColor" fillRule="evenodd" d="M9.911 14.26a1 1 0 0 1-1.344 1.48l-4.134-3.752a1.333 1.333 0 0 1 0-1.975L8.567 6.26a1 1 0 1 1 1.344 1.48L7.423 10h18.604a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H16.012a1 1 0 1 1 0-2h10.015V12H7.422l2.49 2.26" /></svg>);

export const StartOverIcon = createIcon(StartOverIcon16, StartOverIcon24, StartOverIcon32, "StartOverIcon");