/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const SyncIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path d="M9.97 6.72a.75.75 0 0 0 1.06 1.06l2.75-2.75a.75.75 0 0 0 0-1.06l-2.75-2.75a.75.75 0 1 0-1.06 1.06l1.47 1.47H2.75a.75.75 0 0 0 0 1.5h8.69zm-5.41 4.03h8.69a.75.75 0 0 1 0 1.5H4.56l1.47 1.47a.75.75 0 1 1-1.06 1.06l-2.75-2.75a.75.75 0 0 1 0-1.06l2.75-2.75a.75.75 0 0 1 1.06 1.06z" /></svg>);
const SyncIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path d="M16.53 4.22a.75.75 0 1 0-1.06 1.06l1.97 1.97H4.75a.75.75 0 0 0 0 1.5h12.69l-1.97 1.97a.75.75 0 1 0 1.06 1.06l3.25-3.25a.75.75 0 0 0 0-1.06zm-8 9.06a.75.75 0 1 0-1.06-1.06l-3.25 3.25a.75.75 0 0 0 0 1.06l3.25 3.25a.75.75 0 0 0 1.06-1.06l-1.97-1.97h12.69a.75.75 0 0 0 0-1.5H6.56z" /></svg>);
const SyncIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path d="M20.293 14.293a1 1 0 0 0 1.414 1.414l4-4a1 1 0 0 0 0-1.414l-4-4a1 1 0 1 0-1.414 1.414L22.586 10H7a1 1 0 1 0 0 2h15.586zm-8.586 3.414a1 1 0 0 0-1.414-1.414l-4 4a1 1 0 0 0 0 1.414l4 4a1 1 0 0 0 1.414-1.414L9.414 22H25a1 1 0 1 0 0-2H9.414z" /></svg>);

export const SyncIcon = createIcon(SyncIcon16, SyncIcon24, SyncIcon32, "SyncIcon");