/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const TagIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="m8.688 3.076 3.933.393.393 3.933-5.095 5.096L3.592 8.17zm5.405.04a1.25 1.25 0 0 0-1.12-1.12L8.72 1.572a1.25 1.25 0 0 0-1.008.36L2.355 7.287a1.25 1.25 0 0 0 0 1.768l4.68 4.68a1.25 1.25 0 0 0 1.768 0l5.356-5.356a1.25 1.25 0 0 0 .36-1.008zm-3.817 2.698a.714.714 0 1 0 1.01-1.01.714.714 0 0 0-1.01 1.01" /></svg>);
const TagIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M19.969 5.374a1.5 1.5 0 0 0-1.343-1.343l-5.707-.57a1.5 1.5 0 0 0-1.21.431l-7.224 7.224a1.5 1.5 0 0 0 0 2.121l6.278 6.278a1.5 1.5 0 0 0 2.12 0l7.225-7.224a1.5 1.5 0 0 0 .432-1.21zm-1.493.15.571 5.707-7.224 7.223-6.277-6.277 7.223-7.224zm-3.461 3.5a1 1 0 1 0 1.414-1.415 1 1 0 0 0-1.414 1.414" /></svg>);
const TagIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="m16.979 7.369 6.96.696.696 6.96-8.853 8.852-7.656-7.656zm8.93.293a1.75 1.75 0 0 0-1.568-1.567l-7.281-.728a1.75 1.75 0 0 0-1.412.504l-9.113 9.113a1.75 1.75 0 0 0 0 2.475l8.01 8.009a1.75 1.75 0 0 0 2.475 0l9.113-9.113a1.75 1.75 0 0 0 .504-1.412zm-6.182 4.661a1.236 1.236 0 1 0 1.748-1.748 1.236 1.236 0 0 0-1.748 1.748" /></svg>);

export const TagIcon = createIcon(TagIcon16, TagIcon24, TagIcon32, "TagIcon");