/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const TextLessonIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path d="M1.75 2a.75.75 0 0 0 0 1.5h1v2.75a.75.75 0 0 0 1.5 0V3.5h1a.75.75 0 0 0 0-1.5zM7.5 6.25a.75.75 0 0 1 .75-.75h6a.75.75 0 0 1 0 1.5h-6a.75.75 0 0 1-.75-.75M1.75 9a.75.75 0 0 0 0 1.5h12.5a.75.75 0 0 0 0-1.5zm0 3.5a.75.75 0 0 0 0 1.5h6a.75.75 0 0 0 0-1.5zM8.25 2a.75.75 0 0 0 0 1.5h6a.75.75 0 0 0 0-1.5z" /></svg>);
const TextLessonIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path d="M3.75 4.5a.75.75 0 0 0 0 1.5H5.5v3.75a.75.75 0 0 0 1.5 0V6h1.75a.75.75 0 0 0 0-1.5zm8.5 0a.75.75 0 0 0 0 1.5h8a.75.75 0 0 0 0-1.5zm0 4.5a.75.75 0 0 0 0 1.5h8a.75.75 0 0 0 0-1.5zM3 14.25a.75.75 0 0 1 .75-.75h16.5a.75.75 0 0 1 0 1.5H3.75a.75.75 0 0 1-.75-.75M3.75 18a.75.75 0 0 0 0 1.5H12a.75.75 0 0 0 0-1.5z" /></svg>);
const TextLessonIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path d="M5 6a1 1 0 0 0 0 2h2v5a1 1 0 1 0 2 0V8h2a1 1 0 1 0 0-2zm11 0a1 1 0 1 0 0 2h11a1 1 0 1 0 0-2zm0 6a1 1 0 1 0 0 2h11a1 1 0 1 0 0-2zM4 19a1 1 0 0 1 1-1h22a1 1 0 1 1 0 2H5a1 1 0 0 1-1-1m1 5a1 1 0 1 0 0 2h11a1 1 0 1 0 0-2z" /></svg>);

export const TextLessonIcon = createIcon(TextLessonIcon16, TextLessonIcon24, TextLessonIcon32, "TextLessonIcon");