/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const UnderlineIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M2.134 1.752a.75.75 0 0 1 .75-.75h2.412a.75.75 0 0 1 0 1.5H4.77V7.42a3.24 3.24 0 1 0 6.48 0V2.5h-.528a.75.75 0 0 1 0-1.499h2.414a.75.75 0 0 1 0 1.5h-.386V7.42a4.74 4.74 0 0 1-9.48 0V2.5h-.387a.75.75 0 0 1-.75-.749m.75 11.751a.75.75 0 0 0 0 1.5h10.23a.75.75 0 0 0 0-1.5z" /></svg>);
const UnderlineIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M5 3.75A.75.75 0 0 1 5.75 3h2.94a.75.75 0 0 1 0 1.5h-.717v7.957a4.028 4.028 0 0 0 8.056 0V4.5h-.721a.75.75 0 0 1 0-1.5h2.943a.75.75 0 0 1 0 1.5h-.722v7.957a5.528 5.528 0 0 1-11.056 0V4.5h-.724A.75.75 0 0 1 5 3.75m.755 15.75a.75.75 0 0 0 0 1.5h12.499a.75.75 0 1 0 0-1.5z" /></svg>);
const UnderlineIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M5.988 5a1 1 0 0 1 1-1h4.234a1 1 0 1 1 0 2H10.11v10.12a5.88 5.88 0 0 0 11.758 0V6H20.75a1 1 0 1 1 0-2h4.237a1 1 0 1 1 0 2H23.87v10.12a7.88 7.88 0 1 1-15.759 0V6H6.988a1 1 0 0 1-1-1M7 26a1 1 0 1 0 0 2h18a1 1 0 1 0 0-2z" /></svg>);

export const UnderlineIcon = createIcon(UnderlineIcon16, UnderlineIcon24, UnderlineIcon32, "UnderlineIcon");