/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const UploadIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path d="M11.37 4.973a.75.75 0 0 1-1.06 0l-1.56-1.56v7.32a.75.75 0 0 1-1.5 0v-7.32l-1.56 1.56a.75.75 0 0 1-1.06-1.06l2.604-2.605a1.083 1.083 0 0 1 1.532 0l2.604 2.604a.75.75 0 0 1 0 1.06" /><path d="M3.5 11.4v2.091h9v-2.09a.75.75 0 0 1 1.5 0v2.34c0 .69-.56 1.25-1.25 1.25h-9.5c-.69 0-1.25-.56-1.25-1.25v-2.34a.75.75 0 0 1 1.5 0" /></svg>);
const UploadIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path d="M16.155 7.767a.75.75 0 0 1-1.06 0L12.75 5.423v9.842a.75.75 0 0 1-1.5 0V5.423L8.906 7.767a.75.75 0 1 1-1.06-1.061l3.388-3.389a1.083 1.083 0 0 1 1.532 0l3.389 3.389a.75.75 0 0 1 0 1.06M5 19.51a1.5 1.5 0 0 0 1.5 1.5h11a1.5 1.5 0 0 0 1.5-1.5V17a.75.75 0 0 0-1.5 0v2.51h-11V17A.75.75 0 0 0 5 17z" /></svg>);
const UploadIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path d="M21.926 10.788a1 1 0 0 1-1.414 0L17 7.276v13.366a1 1 0 1 1-2 0V7.276l-3.512 3.512a1 1 0 0 1-1.414-1.414l4.983-4.983a1.333 1.333 0 0 1 1.886 0l4.983 4.983a1 1 0 0 1 0 1.414" /><path d="M6 26a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-4a1 1 0 1 0-2 0v4H8v-4a1 1 0 1 0-2 0z" /></svg>);

export const UploadIcon = createIcon(UploadIcon16, UploadIcon24, UploadIcon32, "UploadIcon");