/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const VideoCameraDisabledIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M2.04 1.156a.75.75 0 0 0-.877 1.193l.043.043A1 1 0 0 0 1 3v10a1 1 0 0 0 1 1h9a1 1 0 0 0 .985-.829l1.792 1.792a.749.749 0 0 0 1.194-.877zm11.758 10.343.074.043A.75.75 0 0 0 15 10.894V5.106a.75.75 0 0 0-1.128-.648L12 5.55V3a1 1 0 0 0-1-1H4.299l1.5 1.5H10.5v.454L10.499 4v4.2zM2.5 12.5V3.686l8 8v.814zm9.499-3.787 1.501.876V6.412l-1.501.876z" /></svg>);
const VideoCameraDisabledIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M3.866 2.873a.75.75 0 0 0-.879 1.194l.935.936A1 1 0 0 0 3 6v12a1 1 0 0 0 1 1h13a1 1 0 0 0 .666-.254l2.26 2.26a.75.75 0 0 0 1.195-.878zm15.228 13.106 1.29 1.009A1 1 0 0 0 22 16.2V8a1 1 0 0 0-1.6-.8L18 9V6a1 1 0 0 0-1-1H8.114l1.5 1.5H16.5v6.886zM4.5 6.5h.92l11 11H4.5zm16 8.676L18 13.22v-2.346L20.5 9z" /></svg>);
const VideoCameraDisabledIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M5.435 4.04a1 1 0 0 0-1.398 1.43l.86.861A2 2 0 0 0 4 8.001v16a2 2 0 0 0 2 2h15a2 2 0 0 0 1.961-1.607l3.602 3.602a1 1 0 0 0 1.43-1.398zM26.67 22.447l.775.517A1 1 0 0 0 29 22.132V9.869a1 1 0 0 0-1.555-.832L23 12V8a2 2 0 0 0-2-2H10.223l2 2H21v8.777zM6 8h.567L21 22.433V24H6zm21 12.263-4-2.667v-3.192l4-2.667z" /></svg>);

export const VideoCameraDisabledIcon = createIcon(VideoCameraDisabledIcon16, VideoCameraDisabledIcon24, VideoCameraDisabledIcon32, "VideoCameraDisabledIcon");