/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../create-icon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const VideoIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M2.5 12.5v-9h11v9zM1 3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1zm10 5.65a.75.75 0 0 0 0-1.3L6.625 4.825a.75.75 0 0 0-1.125.65v5.05a.75.75 0 0 0 1.125.65zM7 6.773 9.125 8 7 9.227z" /></svg>);
const VideoIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M4.5 6.5h15v11h-15zM3 6.5A1.5 1.5 0 0 1 4.5 5h15A1.5 1.5 0 0 1 21 6.5v11a1.5 1.5 0 0 1-1.5 1.5h-15A1.5 1.5 0 0 1 3 17.5zm12.375 6.15a.75.75 0 0 0 0-1.3l-4.5-2.598a.75.75 0 0 0-1.125.65v5.196a.75.75 0 0 0 1.125.65l4.5-2.598m-4.125.649v-2.598L13.5 12z" /></svg>);
const VideoIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M6 8h20v16H6zM4 8a2 2 0 0 1 2-2h20a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2zm16.5 8.866a1 1 0 0 0 0-1.732l-6-3.464a1 1 0 0 0-1.5.866v6.928a1 1 0 0 0 1.5.866zm-5.5.866v-3.464L18 16z" /></svg>);

export const VideoIcon = createIcon(VideoIcon16, VideoIcon24, VideoIcon32, "VideoIcon");