/**
 * This file is generated by the generate-components script. Do not edit directly.
 */
/* eslint-disable */
import { createIcon } from "../createIcon.tsx";
import { forwardRef, type Ref, type SVGProps } from "react";

const WebinarLessonIcon16 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}><path fillRule="evenodd" d="M8 5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M7 7.5a1 1 0 1 1 2 0 1 1 0 0 1-2 0" /><path fillRule="evenodd" d="M2 14h12a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1m.5-10.5v9h2.17a3 3 0 0 1 2.83-2h1c1.306 0 2.418.835 2.83 2h2.17v-9zm6 8.5c.444 0 .843.193 1.118.5H6.382c.275-.307.674-.5 1.118-.5z" /></svg>);
const WebinarLessonIcon24 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={24} height={24} viewBox="0 0 24 24" ref={ref} {...props}><path fillRule="evenodd" d="M12 8a3 3 0 1 0 0 6 3 3 0 0 0 0-6m-1.5 3a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0" /><path fillRule="evenodd" d="M4.5 19h15a1.5 1.5 0 0 0 1.5-1.5v-11A1.5 1.5 0 0 0 19.5 5h-15A1.5 1.5 0 0 0 3 6.5v11A1.5 1.5 0 0 0 4.5 19m15-12.5h-15v11h2.79A4 4 0 0 1 11 15h2a4 4 0 0 1 3.71 2.5h2.79zm-6.5 10c.818 0 1.544.393 2 1H9c.456-.607 1.182-1 2-1z" /></svg>);
const WebinarLessonIcon32 = forwardRef((props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => <svg width={32} height={32} viewBox="0 0 32 32" ref={ref} {...props}><path fillRule="evenodd" d="M16 11a4 4 0 1 0 0 8 4 4 0 0 0 0-8m-2 4a2 2 0 1 1 4 0 2 2 0 0 1-4 0" /><path fillRule="evenodd" d="M6 26h20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2M26 8H6v16h3.341c.824-2.33 3.047-4 5.659-4h2a6 6 0 0 1 5.659 4H26zm-9 14c1.48 0 2.773.804 3.465 2h-8.93A4 4 0 0 1 15 22z" /></svg>);

export const WebinarLessonIcon = createIcon(WebinarLessonIcon16, WebinarLessonIcon24, WebinarLessonIcon32, "WebinarLessonIcon");