name: Setup Node and PNPM

runs:
    using: composite
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
            check-latest: true
            cache: pnpm
            cache-dependency-path: pnpm-lock.yaml
