name: Restore Turborepo cache

runs:
    using: composite
    steps:
        -   name: Restore Turborepo cache
            id: cache-turborepo-restore
            uses: actions/cache/restore@v4
            with:
                key: ${{ runner.os }}-turborepo-${{ github.sha }}
                restore-keys: |
                    ${{ runner.os }}-turborepo-
                path: .turbo
