name: Changesets

on:
    push:
        branches: [ "main" ]
env:
    CI: true

jobs:
    version:
        runs-on: ubuntu-latest
        permissions:
            id-token: write # required for provenance https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions
            contents: write
            pull-requests: write

        steps:
            -   name: Setup Node and PNPM
                uses: ./../actions/setup.yml

            -   name: Create release Pull Request or publish to NPM
                uses: changesets/action@v1
                with:
                    commit: "ci(changesets): version packages"
                    title: "Changeset: New Version"
                    publish: pnpm run ci-release
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    NPM_TOKEN: ${{ secrets.WORKLEAP_NPM_TOKEN }}
