name: CI

# Pnpm setup based on https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    CI: true

concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup Node and PNPM
                uses: ./.github/composite-actions/setup

            -   name: Install dependencies
                run: pnpm i --frozen-lockfile

            -   name: Restore Turborepo cache
                uses: ./.github/composite-actions/restore-turborepo

            -   name: Generate documentation
                run: pnpm doc:generate

            -   name: Build packages
                run: pnpm build:pkg

            -   name: Build sample apps
                run: pnpm build:apps

            -   name: Lint
                run: pnpm lint

            -   name: Test
                run: pnpm test

            -   name: Restore Turborepo cache
                uses: ./.github/composite-actions/save-turborepo
